### PR TITLE
<xlocale>: codecvt_base::result should be an enum type

### LINKED ISSUE #266: <xlocale>: codecvt_base::result should be an enum type
https://github.com/microsoft/STL/blob/58c5c4d628abeb22b0028ff479853d7d8212d8a7/stl/inc/xlocale#L664-L670

https://eel.is/c++draft/locale.codecvt mandates `enum result { ok, partial, error, noconv };`.

### PR DESCRIPTION
**Pull request by lozinska**
# Description
Adding name 'result' to enum type.

Resolves #266 

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [ ] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [ ] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [ ] These changes were written from scratch using only this repository and
  the C++ Working Draft as a reference (and any other cited standards).
  If they were derived from a project that's already listed in NOTICE.txt,
  that's fine, but please mention it. If they were derived from any other
  project (including Boost and libc++, which are not yet listed in
  NOTICE.txt), you *must* mention it here, so we can determine whether the
  license is compatible and what else needs to be done.

### CODE REVIEW

**Comment by miscco** [comment]
It seems that you did not jump back to master when checking out the new branch so your commits from #278 are still present.

**Comment by SuperWig** [comment]
This issue is for VNext which I don't think they're taking PR's for right now as that branch isn't up on GitHub yet.

Though other than what @miscco pointed out, clang-format and the build are failing. If I'm not mistaken `enum result` is supposed to replace this type alias.
https://github.com/microsoft/STL/blob/25c4cd7d8ad7930dc0ade8b0388dc8da4c0a956e/stl/inc/xlocale#L670

**Comment by lozinska** [comment]
Hi @SuperWig you mentioned in comment above that VNext do not accept PR as right now, so I was wondering if it is a need for me to work on this PR?
Thank you

**Comment by crackedmind** [comment]
About vNext you need to ask @StephanTLavavej

**Comment by StephanTLavavej** [comment]
That's correct - the vNext branch doesn't exist yet, and we have substantial work to do before it'll be ready for PRs. (Currently all of our vNext work is stranded in an outdated branch of Team Foundation Version Control, and will need to be carefully rethought and hand-ported to our modern sources here.) We'll definitely be doing this work, but we don't have a firm schedule yet; I don't believe that the vNext branch will be available before the second half of calendar year 2020.

Thank you for looking into this, @lozinska. I'm going to close the PR due to branch unavailability, but we appreciate your work, and apologize for not being ready yet.

Additionally, we currently have 19 open issues tagged vNext - I'll go through all of them and add a note quickly explaining that they're binary-breaking and will require a separate branch.

In this particular case, the one-line change is binary-breaking because it changes a publicly accessible type. For example, user-defined functions taking `codecvt_base::result` as a parameter would have their mangled names affected by any change to that type. Therefore, this change could prevent user LIBs from linking, or DLLs from loading, so it can't be shipped in the VS 2019 compatible release series.

**Pull request closed without merging**
