### PR TITLE
Investigate and Fix Potential Memory Leak in at_thread_exit Machinery Using CRT Block Technique

### PR DESCRIPTION
**Pull request by Arup-Chauhan**
Raised this draft PR investigates a potential memory leak in the `at_thread_exit` machinery using `_CrtDumpMemoryLeaks` (#4418)

If the leak is confirmed will fix it using the `CRT block` technique. 

Currently, I will follow these steps:

1. **Investigate Memory Leak**: Use `_CrtDumpMemoryLeaks` to check if the leak occurs during `at_thread_exit`.
2. **Apply CRT Block Technique**: If a leak is found, wrap the problematic code with memory tracking blocks to manage allocations properly.
3. **Verify the Fix**: Run the test again to ensure no memory leaks are reported after applying the fix.
4. **Add a Unit Test**: Create a test case that validates the absence of memory leaks in the `at_thread_exit` machinery.

Feedback is welcome on the initial investigation and direction.

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
Not sure whether a PR is opened at the current stage. Perhaps we can try to add unit cast first to catch the bug and then fix it.

**Comment by Arup-Chauhan** [comment]
> Not sure why a PR is opened at the current stage. Perhaps we can try to add unit cast first to catch the bug and then fix it.

I raised the PR to document my steps, hence kept the PR in the draft stage, will keep updating this as I work on this and then marj it ready.

Also, if a leak is not found then at least we could get the test coverage for it.

**Comment by CaseyCarter** [comment]
Closing the PR since there's nothing here to review. Feel free to ask questions or solicit comments about your intended approach in #4418, or to open another PR when you have potential changes to merge or to get comment on.

**Comment by Arup-Chauhan** [comment]
> Closing the PR since there's nothing here to review. Feel free to ask questions or solicit comments about your intended approach in #4418, or to open another PR when you have potential changes to merge or to get comment on.


Understood @CaseyCarter!

**Pull request closed without merging**
