### PR TITLE
Finish Fixing Atomic Initialization

### LINKED ISSUE #336: P0883R2 Fixing Atomic Initialization
[P0883R2](https://wg21.link/P0883R2) Fixing Atomic Initialization

As [C++17/20 Features and Fixes in Visual Studio 2019](https://devblogs.microsoft.com/cppblog/cpp17-20-features-and-fixes-in-vs-2019/) announced, Miya implemented the core functionality of this feature in VS 2019 16.0:

> P0883 "Fixing atomic initialization", which changes `std::atomic` to value-initialize the contained `T` rather than default-initializing it, was implemented (also by Miya) when using Clang/LLVM with our standard library. This is currently disabled for C1XX as a workaround for a bug in `constexpr` processing.

https://github.com/microsoft/STL/blob/8f4c8163775d665d80642044ce27c4bc696127ce/stl/inc/atomic#L1446-L1450

Now that P0883 has been voted into the Standard, there are at least three more things to do:

* C1XX fixed the `constexpr` initialization bug (Microsoft-internal VSO-406237), so we need to remove the workaround.
* P0883 was updated to deprecate things. We need to implement those deprecations, and double-check that we've implemented everything that was voted in.
* Feature-test macro as of WG21-N4842:
`#define __cpp_lib_atomic_value_initialization 201911L`

### PR DESCRIPTION
**Pull request by AdamBucior**
# Description

Resolves #336. The only problem is that I don't know how to signal deprecation of `ATOMIC_VAR_INIT` and `ATOMIC_FLAG_INIT` macros.

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [x] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

**Comment by codicodi** [comment]
You can generate a message on macro use like this:

```
#define HELLO_DEPRECATION_WARNING __pragma(message ("Warning: HELLO is deprecated"))
#define HELLO HELLO_DEPRECATION_WARNING "Hello"
```
It doesn't count as a warning from compiler's perspective though (doesn't turn into error with `/WX` or `-Werror`).

**Comment by sylveon** [comment]
You can use a type to differentiate the use of the `ATOMIC_*_INIT` operators/constructors, and then deprecate those: https://godbolt.org/z/anYSGd

**Comment by BillyONeal** [comment]
I agree we don't need to bend over backwards to mark the macro as deprecated.

**Comment by BillyONeal** [comment]
@CaseyCarter AFAIK the compiler that ships with 2019 16.5 Preview 2 should have that fixed, so I think we can merge this as soon as that ships.

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
