### PR TITLE
Update boost-math from 1.77 to 1.80

### PR DESCRIPTION
**Pull request by AtariDreams**
This is the latest stable version of boost-math

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
Probably a duplicate of #3077.

**Comment by AtariDreams** [comment]
It is not a duplicate, though both are similar

**Comment by strega-nil-ms** [comment]
How is it not a duplicate? (with fewer changes)

**Comment by AtariDreams** [comment]
@fsb4000 thoughts?

**Pull request closed without merging**
