### PR TITLE
Updated to MAY21

### LINKED ISSUE #1896: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to May 2021
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/65eb5077778a11cc4abac88b5fd5d0a25a2dcd19/stl/inc/yvals_core.h#L524

Previous issue: #1799

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Resolves #1896

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks!

I've edited your PR description to say "Resolves" instead of "Solves" - this is because GitHub (as [their documentation](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) explains) considers various forms of "Closes", "Fixes", and "Resolves" to be special - using them will "link" a pull request to an issue, such that merging the PR will automatically close the issue. Anything else will "mention" an issue (appearing in its history) but won't set up that auto-closing link. Not a problem, just thought I'd mention it for the future! :smiley_cat:

**Comment by himanshu007-creator** [comment]
> Thanks!
> 
> I've edited your PR description to say "Resolves" instead of "Solves" - this is because GitHub (as [their documentation](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) explains) considers various forms of "Closes", "Fixes", and "Resolves" to be special - using them will "link" a pull request to an issue, such that merging the PR will automatically close the issue. Anything else will "mention" an issue (appearing in its history) but won't set up that auto-closing link. Not a problem, just thought I'd mention it for the future! 😺

Sure! I genrally use resolves, missed this time😬

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Apologies for the delay here - we're usually faster at merging PRs, but our process is semi-manual (as we have to mirror GitHub PRs to the internal MSVC repo where the product is officially built) and several members of the team including me have been on vacation :beach_umbrella:. I believe we should be able to merge your PR next week, stay tuned.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! :tada: :smiley_cat:

**Pull request merged**
