### PR TITLE
Add tr1 testsuite

### PR DESCRIPTION
**Pull request by cbezault**
Description
===========
Enable tr1 tests.

### CODE REVIEW

**Comment by cbezault** [comment]
I believe that `_tempnam` in wchar1 is returning the same file name to multiple processes which causes a race between test processes. [`_tempanm`'s documentation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/tempnam-wtempnam-tmpnam-wtmpnam?view=vs-2019) states that the directory provided to it is ignored if `TMP` is a valid directory.

**Comment by cbezault** [comment]
I'd like to merge this PR without a green checkmark. I've opened #655 to deal with the single test failure.

**Comment by CaseyCarter** [comment]
> I'd like to merge this PR without a green checkmark. I've opened #655 to deal with the single test failure.

Why not simply merge that change into this PR?

**Comment by cbezault** [comment]
Re-running takes so long 😢. But you're right. I'll wait until after #655 .

**Comment by CaseyCarter** [comment]
> Re-running takes so long 😢

We have been so spoiled by our ten-minute CI ;)

**Pull request merged**
