### PR TITLE
Update yvals_core.h

### LINKED ISSUE #4292: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to January 2024
Explanation on our wiki: [Macro _MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code: https://github.com/microsoft/STL/blob/a8888806c6960f1687590ffd4244794c753aa819/stl/inc/yvals_core.h#L884

Previous issue: #4224

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by Itsbabin**
fixed #4292 issue

Update yvals_core.h file to January 2024.

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! We periodically merge PRs in a semi-manual batching process, so we'll likely merge your PR next week (I am technically still on vacation :joy_cat:).

**Review by fsb4000 — APPROVED** [review]

**Comment by Itsbabin** [comment]
[StephanTLavavej](https://github.com/StephanTLavavej)  
thanks

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, congratulations on your first microsoft/STL commit, and happy new year! :tada: :heart_eyes_cat: :calendar:

**Pull request merged**
