### PR TITLE
Tests using /analyze:only should also use /analyze:autolog-

### LINKED ISSUE #1416: Tests using /analyze:only should also use /analyze:autolog-
Several of our test configurations compile with `/analyze:only`. This emits a `.nativecodeanalysis.xml` file that we're never *ever* interested in. There's a (new?) compiler option to suppress this, `/analyze:autolog-`, which can be used with `/analyze:only`. Example:

```
C:\Temp>type meow.cpp && echo --- && dir /b meow.* && echo ---
#include <iostream>
using namespace std;

int f(int x, int y) {
    if (!x & y) {
        return 1;
    }
    return 0;
}

int main() {
    cout << "Hello, world!" << endl;
}
---
meow.cpp
---

C:\Temp>cl /EHsc /nologo /W4 /analyze meow.cpp && echo --- && dir /b meow.* && echo --- && del meow.exe meow.nativecodeanalysis.xml meow.obj
meow.cpp
C:\Temp\meow.cpp(5) : warning C6290: Bitwise operation on logical result:  ! has higher precedence than &.  Use && or (!(x & y)) instead.
---
meow.cpp
meow.exe
meow.nativecodeanalysis.xml
meow.obj
---

C:\Temp>cl /EHsc /nologo /W4 /analyze:autolog- meow.cpp && echo --- && dir /b meow.* && echo --- && del meow.exe meow.nativecodeanalysis.xml meow.obj
meow.cpp
C:\Temp\meow.cpp(5) : warning C6290: Bitwise operation on logical result:  ! has higher precedence than &.  Use && or (!(x & y)) instead.
---
meow.cpp
meow.exe
meow.obj
---

C:\Temp>cl /EHsc /nologo /W4 /analyze:only meow.cpp && echo --- && dir /b meow.* && echo --- && del meow.exe meow.nativecodeanalysis.xml meow.obj
meow.cpp
C:\Temp\meow.cpp(5) : warning C6290: Bitwise operation on logical result:  ! has higher precedence than &.  Use && or (!(x & y)) instead.
---
meow.cpp
meow.nativecodeanalysis.xml
---

C:\Temp>cl /EHsc /nologo /W4 /analyze:only /analyze:autolog- meow.cpp && echo --- && dir /b meow.* && echo ---
meow.cpp
C:\Temp\meow.cpp(5) : warning C6290: Bitwise operation on logical result:  ! has higher precedence than &.  Use && or (!(x & y)) instead.
---
meow.cpp
---
```

In #1394, I've pushed a commit to change plain `/analyze` to `/analyze:autolog-`. We should follow this up with another PR to change `/analyze:only` to `/analyze:only /analyze:autolog-`.

Aside: `/analyze:only` skips codegen, so we've generally paired it with a non-`/analyze` configuration, e.g.
https://github.com/microsoft/STL/blob/2b4cf99c044176637497518294281046439a1bcc/tests/std/tests/usual_matrix.lst#L20-L21

### PR DESCRIPTION
**Pull request by Arzaghi**
Closes #1416

### CODE REVIEW

**Comment by Arzaghi** [comment]
Azure /start

**Comment by StephanTLavavej** [comment]
The tests seem to have passed now - but I don't know why they appeared to have stalled, or why the Azure Pipelines bot said you didn't have sufficient privileges - we haven't changed anything recently.

**Comment by Arzaghi** [comment]
> The tests seem to have passed now - but I don't know why they appeared to have stalled, or why the Azure Pipelines bot said you didn't have sufficient privileges - we haven't changed anything recently.

The bot said that, because I tried to to re-trigger the pipeline manually and then I edited my comment.

**Review by cbezault — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for improving the test harness and reducing the amount of output that it writes to the disk! :smile_cat:

**Pull request merged**
