### PR TITLE
Update VMSS pool to one with vs16.7p2

### PR DESCRIPTION
**Pull request by cbezault**

### CODE REVIEW

**Comment by cbezault** [comment]
I have no idea why edg isn't getting found :(.

**Comment by StephanTLavavej** [comment]
I guess the next step to investigate is to prepare a VM with the script, and manually try to invoke `cl /BE` and see what happens?

**Comment by cbezault** [comment]
Yup that would do it. You could also fuss around with making commits to this PR to do some debugging.

**Comment by AlexGuteniev** [comment]
As there's p2 already, can you just try again with p2?

**Comment by cbezault** [comment]
Sure

**Comment by cbezault** [comment]
Same problem

**Comment by cbezault** [comment]
Looks like the CoreIde component doesn't exist anymore and we're silently failing when we provision the machines.
image

**Comment by StephanTLavavej** [comment]
To make investigations easier in the future, when command-line install fails like this, are logs emitted anywhere (or can we add an option to request them)? I guess we could reproduce this at will any time by attempting to install a nonexistent component.

**Comment by StephanTLavavej** [comment]
Thanks for taking care of this update! I'll have to learn how to do the next one. :smile_cat:

**Pull request merged**
