### PR TITLE
`<thread>`: implement LWG-3788

### PR DESCRIPTION
**Pull request by strega-nil-ms**
We implemented self-assign by stopping and joining; this was a bad idea, and there is now an LWG issue to say that we shouldn't do that.

See LWG-3788.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
@strega-nil-ms If possible, I strongly recommend writing a Proposed Resolution for LWG-3788 if you want it to be accepted this decade - issues without Proposed Resolutions tend to linger for years, while those with simple and uncontroversial Proposed Resolutions can be quickly accepted within a meeting or two.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
This seems to be somewhat more daring than we usually are for not-yet-accepted LWG issues (that change the Standardese 180 degrees, instead of merely clarifying something ambiguous). In the past, we've been burned by speculatively implementing "obviously correct" fixes that later turned out to be controversial (e.g. `future`'s blocking destructor, IIRC).

That said, I think it's reasonable to be slightly daring here, as the existing self-move-assign behavior is so wacky, being a no-op is much more intuitive, and (importantly) this is a hopefully obscure case in relatively new machinery, so the possible impact is small.

:white_check_mark: No modules impact.

**Review by CaseyCarter — APPROVED** [review]

**Comment by strega-nil-ms** [comment]
LWG has put forward a resolution to this issue that the thread seems happy about.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main` to resolve a simple merge conflict with an updated WP citation in `<thread>` - this PR's change supersedes that.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this wacky behavior in both the Standard and our implementation! :joy_cat: :smile_cat: :tada:

**Pull request merged**
