### PR TITLE
Document `_Ref_fn`'s *raison d'etre*

### LINKED ISSUE #4027: Why shouldn't we replace `_Ref_fn` with `reference_wrapper`?
In #4025 there's attemption to strengthen the exception specification of `_Ref_fn::operator()`.

Given the standard class template `std::reference_wrapper` is already a invocable wrapper and its `operator()` has a propagating exception specification (thanks to LWG-3764), it seems OK to replace the uses of `_Ref_fn` with `reference_wrapper`.

Pros:
- user codes should only use `reference_wrapper`, so we might be able to instantiate less specializations.

Cons:
- `reference_wrapper` is slightly heavier than `_Ref_fn`;
- `reference_wrapper` is assignable, which might be unwanted for the internal details of the implementation.

### PR DESCRIPTION
**Pull request by CaseyCarter**
(Pardon my French!)

Fixes #4027

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
:scroll: :scroll: :scroll:
===

**Comment by matt77hias** [comment]
Pardon my ignorance, but what is the meaning of "enregistered" in this context?

**Comment by StephanTLavavej** [comment]
@matt77hias It means "passed via processor registers, instead of being placed on the stack and passed via address".

**Pull request merged**
