### PR TITLE
Add `[[msvc::lifetimebound]]` to `minmax`

### PR DESCRIPTION
**Pull request by statementreply**
Works towards #3754. Works towards #2094.

This PR adds `[[msvc::lifetimebound]]` to `std::minmax` and `std::ranges::minmax`, which are more error-prone than `std::min`/`std::max` but not as widely used.

`#define _SILENCE_LIFETIMEBOUND_WARNING` to suppress the warning.

```
C:\Users\He\source\repos\STL\out>type test.cpp
```
```cpp
#include <algorithm>

int square(int x) {
    return x * x;
}

int square_diff(int x, int y) {
    const auto [min, max] = std::minmax(square(x), square(y));
    return max - min;
}
```
```
C:\Users\He\source\repos\STL\out>clang -Wall -Wextra -std=c++17 -c test.cpp
test.cpp:8:41: warning: temporary whose address is used as value of local variable '[min, max]' will be destroyed at the
      end of the full-expression [-Wdangling]
    const auto [min, max] = std::minmax(square(x), square(y));
                                        ^~~~~~~~~
test.cpp:8:52: warning: temporary whose address is used as value of local variable '[min, max]' will be destroyed at the
      end of the full-expression [-Wdangling]
    const auto [min, max] = std::minmax(square(x), square(y));
                                                   ^~~~~~~~~
2 warnings generated.

C:\Users\He\source\repos\STL\out>set Esp.Extensions=CppCoreCheck.dll

C:\Users\He\source\repos\STL\out>cl /EHsc /W4 /std:c++17 /c /analyze:plugin EspXEngine.dll /analyze:ruleset ..\tests\std\rulesets\stl.ruleset test.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.37.32705 版
版权所有(C) Microsoft Corporation。保留所有权利。

test.cpp
C:\Users\He\source\repos\STL\out\test.cpp(8) : warning C26815: 指针无关联，因为它指向已销毁的临时实例。
```

### CODE REVIEW

**Comment by strega-nil-ms** [comment]
I really like this personally; however, I want to discuss it in the weekly meeting just to make sure we all agree 😄

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and are in favor of this approach. :smile_cat:

**Review by StephanTLavavej — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Comment by statementreply** [comment]
@StephanTLavavej @strega-nil-ms I pushed changes after you approved.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
I've had to push an additional commit to skip `GH_002094_cpp_core_guidelines` in the MSVC-internal test harness for now. We would need to modify the Perl test machinery to set up the Code Analysis ruleset; it is probably worth doing but can be done later.

FYI @strega-nil-ms as you previously approved.

**Comment by StephanTLavavej** [comment]
Thanks for implementing these new diagnostics! :white_check_mark: :warning: :heart_eyes_cat:

**Pull request merged**
