### PR TITLE
Remove unused functions from `winapisupp.cpp`

### LINKED ISSUE #3926: Why are these functions preserved?
I see that other preserved functions have `_CRTIMP2` or similar, but not these.
Should these really be preserved?

https://github.com/microsoft/STL/blob/ed8150e099f6124c50dd4f002cd2ab8c429a81e3/stl/src/winapisupp.cpp#L157-L175

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Resolve #3926

Mostly a red change

Also repeat `_CRTIMP2` on `__crtGetSystemTimePreciseAsFileTime` -- see #3927

### CODE REVIEW

**Review by CaseyCarter — APPROVED** [review]
Looks like a solid cleanup. I `git grep`ped for all the affected names in the MSVC-internal repo - out of an overabundance of paranoia - and found no other occurrences of the removed names.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
This is great! :heart_eyes_cat:

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main` to resolve a conflict in `stl/src/winapisupp.cpp` where #3900 updated preprocessor comments. Resolved by accepting this PR's code elimination; with only `#if` and `#endif` we don't need arrow comments.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for noticing and eliminating all of this dead code! :zombie: :skull_and_crossbones: :heart_eyes_cat:

**Pull request merged**
