### PR TITLE
`<format>`: delay vformat instantiation

### LINKED ISSUE #2329: `<format>`: `inline` overloads of `vformat()` are costly for throughput
@xiangfan-ms reported (slightly edited for Markdown):

> `<format>` contains 4 overloads of `vformat`. They will specialize lots of other templates. But unlike other functions in STL headers, they are non-template.
> 
> https://github.com/microsoft/STL/blob/178b8406a5647507e759442960f17cd33045cdf5/stl/inc/format#L2885-L2911
> 
> It takes 0.83s to compile `<format>` and all its dependencies. But if I remove the definition of `vformat`, it only takes 0.62s.
> 
> Here are some data:
> 
> |                                     | With definition   | Without definition |
> |------------------------------------:|-------------------|--------------------|
> |                 Overload resolution | 0.185821s / 11218 | 0.075068s / 6024   |
> | Instantiate template specialization | 0.161868s / 1333  | 0.079736s / 583    |
> |                 Specialize template | 0.187945s / 10900 | 0.091789s / 7597   |
> |     Parse default template argument | 0.008578s / 691   | 0.004705s / 403    |

I believe that `template <int = 0>` should be sufficient to delay this throughput cost (i.e. unless and until `vformat()` is actually called), and that it should be unobservable because users are now forbidden from taking the addresses of Standard Library functions. We should probably have comments as to why we're doing this.

@xiangfan-ms replied:

> The `template <int = 0>` trick seems to work (two phase will still try to bind the function call to `std::vformat_to`, but I think the function specialization isn't added to the list to be instantiated).

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2329

### CODE REVIEW

**Comment by fsb4000** [comment]
without the workaround I got bogus warnings treated as errors:
```
Standard Output:
--
test.cpp
C:\Dev\STL\out\build\x64\out\inc\format(1742): error C2220: the following warning is treated as an error
C:\Dev\STL\out\build\x64\out\inc\format(2816): note: see reference to class template instantiation 'std::_Fmt_iterator_buffer<_OutputIt,char,std::_Fmt_buffer_traits>' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::string>
        ]
C:\Dev\STL\out\build\x64\out\inc\format(2889): note: see reference to function template instantiation '_OutputIt std::vformat_to<std::back_insert_iterator<std::string>>(_OutputIt,const std::string_view,const std::format_args)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::string>
        ]
C:\Dev\STL\out\build\x64\out\inc\format(2918): note: see reference to function template instantiation 'std::string std::vformat<0>(const std::string_view,const std::format_args)' being compiled
C:\Dev\STL\tests\std\tests\P1502R1_standard_library_header_units\test.cpp(306): note: see reference to function template instantiation 'std::string std::format<char[8],char[7]>(const std::string_view,const char (&)[8],const char (&)[7])' being compiled
C:\Dev\STL\out\build\x64\out\inc\format(1742): warning C4265: 'std::_Fmt_iterator_buffer<_OutputIt,char,std::_Fmt_buffer_traits>': class has virtual functions, but its non-trivial destructor is not virtual; instances of this class may not be destructed correctly
        with
        [
            _OutputIt=std::back_insert_iterator<std::string>
        ]
C:\Dev\STL\out\build\x64\out\inc\format(2392): warning C4365: 'argument': conversion from '__int64' to 'unsigned __int64', signed/unsigned mismatch
C:\Dev\STL\out\build\x64\out\inc\format(2649): note: see reference to function template instantiation '_OutputIt std::_Fmt_write<_CharT,std::back_insert_iterator<std::_Fmt_buffer<char>>,_Ty>(_OutputIt,const _Float,const std::_Basic_format_specs<_CharT> &,std::_Lazy_locale)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::_Fmt_buffer<char>>,
            _CharT=char,
            _Ty=float,
            _Float=float
        ]
C:\Dev\STL\out\build\x64\out\inc\format(346): note: see reference to function template instantiation '_OutputIt std::_Arg_formatter<_OutputIt,_CharT>::operator ()<float>(_Ty)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::_Fmt_buffer<char>>,
            _CharT=char,
            _Ty=float
        ]
C:\Dev\STL\out\build\x64\out\inc\format(346): note: see reference to function template instantiation '_OutputIt std::_Arg_formatter<_OutputIt,_CharT>::operator ()<float>(_Ty)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::_Fmt_buffer<char>>,
            _CharT=char,
            _Ty=float
        ]
C:\Dev\STL\out\build\x64\out\inc\format(2697): note: see reference to function template instantiation '_OutputIt std::visit_format_arg<std::_Arg_formatter<_OutputIt,_CharT>,_Context>(_Visitor &&,std::basic_format_arg<_Context>)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::_Fmt_buffer<char>>,
            _CharT=char,
            _Context=std::basic_format_context<std::back_insert_iterator<std::_Fmt_buffer<char>>,char>,
            _Visitor=std::_Arg_formatter<std::back_insert_iterator<std::_Fmt_buffer<char>>,char>
        ]
C:\Dev\STL\out\build\x64\out\inc\format(2679): note: while compiling class template member function 'const _CharT *std::_Format_handler<_CharT>::_On_format_specs(const size_t,const _CharT *,const _CharT *)'
        with
        [
            _CharT=char
        ]
C:\Dev\STL\out\build\x64\out\inc\format(934): note: see reference to function template instantiation 'const _CharT *std::_Format_handler<_CharT>::_On_format_specs(const size_t,const _CharT *,const _CharT *)' being compiled
        with
        [
            _CharT=char
        ]
C:\Dev\STL\out\build\x64\out\inc\format(2817): note: see reference to class template instantiation 'std::_Format_handler<char>' being compiled
C:\Dev\STL\out\build\x64\out\inc\format(2889): note: see reference to function template instantiation '_OutputIt std::vformat_to<std::back_insert_iterator<std::string>>(_OutputIt,const std::string_view,const std::format_args)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::string>
        ]
C:\Dev\STL\out\build\x64\out\inc\format(2169): warning C4365: 'argument': conversion from '__int64' to 'unsigned __int64', signed/unsigned mismatch
C:\Dev\STL\out\build\x64\out\inc\format(2206): note: see reference to function template instantiation '_OutputIt std::_Write_integral<_CharT,std::back_insert_iterator<std::_Fmt_buffer<char>>,_Integral>(_OutputIt,const _Integral,std::_Basic_format_specs<_CharT>,std::_Lazy_locale)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::_Fmt_buffer<char>>,
            _CharT=char,
            _Integral=int
        ]
C:\Dev\STL\out\build\x64\out\inc\format(2649): note: see reference to function template instantiation '_OutputIt std::_Fmt_write<_CharT,std::back_insert_iterator<std::_Fmt_buffer<char>>,_Ty>(_OutputIt,const _Integral,const std::_Basic_format_specs<_CharT> &,std::_Lazy_locale)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::_Fmt_buffer<char>>,
            _CharT=char,
            _Ty=int,
            _Integral=int
        ]
C:\Dev\STL\out\build\x64\out\inc\format(334): note: see reference to function template instantiation '_OutputIt std::_Arg_formatter<_OutputIt,_CharT>::operator ()<int>(_Ty)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::_Fmt_buffer<char>>,
            _CharT=char,
            _Ty=int
        ]
C:\Dev\STL\out\build\x64\out\inc\format(334): note: see reference to function template instantiation '_OutputIt std::_Arg_formatter<_OutputIt,_CharT>::operator ()<int>(_Ty)' being compiled
        with
        [
            _OutputIt=std::back_insert_iterator<std::_Fmt_buffer<char>>,
            _CharT=char,
            _Ty=int
        ]
--
```
Shoud the issue to be reduced or is it ok to send the bug report to DevCom as is?

**Comment by CaseyCarter** [comment]
> Should the issue to be reduced or is it ok to send the bug report to DevCom as is?

"Warnings that only appear with modules" is almost certainly the same bug as DevCom-1577182. IIRC there was a fix PR yesterday which may have already landed. I'll verify that the fix works for this case as well, and if so mark this as a workaround for that bug and disable the workaround in the internal test harness.

**Comment by StephanTLavavej** [comment]
I'll look into reducing and reporting this modules bug. :lady_beetle:

**Comment by StephanTLavavej** [comment]
* Reported VSO-1433873 "Standard Library Header Units: Adding `template <int = 0>` to `vformat()` emits warnings C4265 and C4365".
  - Reported internally instead of on DevCom because my repro was partially reduced to "check out and build this branch in my fork of the STL" (which @cdacamar has expressed a preference for, but which DevCom triage presumably finds problematic).
* Adjusted preprocessor logic to `#if defined(__clang__) || defined(__EDG__)`, which distinguishes Clang/EDG from C1XX.
  + In general, `_MSC_VER` is always defined (everyone imitates C1XX), so that doesn't indicate a particular front-end.
* Also adjusted the comments to our conventional `// ^^^ no workaround / workaround vvv` form.
* Extracted the workaround into a macro `_TEMPLATE_INT_0_NODISCARD` (later `#undef`'ed) because it needs to be repeated 4x, and clang-format otherwise produces ugly results.
* Added a comment `improves throughput, see GH-2329`.
  + In general, doing anything subtle that isn't required by the Standard is typically a good reason to have a comment. Mentioned briefly in the issue: "We should probably have comments as to why we're doing this."
* The workaround is repeated for all 4 overloads because the `(string_view, format_args)` overload isn't special - it was just the only one being tested in `P1502R1_standard_library_header_units`. Adding a wide string test case revealed that the compiler issue also affected `(wstring_view, wformat_args)`. So, I'm permanently adding wide coverage. (And slightly enhancing the test case to stringify an `int` `1729`, although that didn't reveal anything.) I didn't think that adding `locale` cases was necessary, but the workaround is almost certainly needed for them too, so I did that.
* I am not sure if the warning C4265 (non-virtual dtor) is valid - `_Fmt_iterator_buffer` certainly has virtual functions with a non-virtual dtor, but we never delete it through a pointer-to-base (it's always a local variable on the stack). However, the warning C4365 occurrences were actually valid - `<format>` was passing the result of pointer subtraction, which is `ptrdiff_t`, to `_Count_separators()` which takes `size_t`, so I'm adding `static_cast`s: https://github.com/microsoft/STL/blob/178b8406a5647507e759442960f17cd33045cdf5/stl/inc/format#L1998

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for improving `<format>` throughput and finding the modules bug here (which has been fixed)! :tada: :chart_with_upwards_trend: :heart_eyes_cat:

**Pull request merged**
