### PR TITLE
`<chrono>`: Add comments for compiler bug workarounds

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
The internal function template `tzdb_list::_Emplace_front` (initially added in #1671) only exists for testing. I found that it's possibly to completely hack in the test codes, so this PR removes it.

After Clang 16 got WG21-P0960R3 implemented, it should be no longer necessary to construct a `tzdb` before calling `emplace_front`. It seems more efficient to directly construct the `tzdb` element within `emplace_front`. But there's some bug in EDG so perhaps it's better to give up the change.

### CODE REVIEW

**Comment by CaseyCarter** [comment]
I guess that was also a workaround for EDG. We'll need to reduce a repro to send to the Edge team and conditionally (or unconditionally) restore the workaround with a transition comment.

**Comment by CaseyCarter** [comment]
Reduced to:
```c++
struct S {
    int x, y;
};

void f(void* ptr) {
    S(13, 42); // Ok
    new S(13, 42); // error: no instance of constructor "S::S" matches
}
```
Which I filed as VSO-2228186 and added to #1621.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
`/clr` hates this technique, reduced and reported as VSO-2231268 "`/clr /std:c++20` rejects sneaky technique to access private data members".

Instead of guarding this test coverage for `/clr`, I'm now inclined to abandon the private data member hack, and merge only the TRANSITION comments for EDG. I think this is adding too much test complexity and the cost for product code is minimal.

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for helping us find and report so many compiler bugs! :lady_beetle: :stopwatch: :joy_cat:

**Pull request merged**
