### PR TITLE
Check if `find_last` can find anything

### LINKED ISSUE #4553: `<algorithm>`: `find_last` is lacking `_Could_compare_equal_to_value_type` check
Here it is missing
https://github.com/microsoft/STL/blob/be81252ed1f5e5fc6d77faca0b5dbbbdae8143a2/stl/inc/algorithm#L2974-L2985

Here it is present
https://github.com/microsoft/STL/blob/be81252ed1f5e5fc6d77faca0b5dbbbdae8143a2/stl/inc/xutility#L5919-L5933

### LINKED ISSUE #4560: Q3 2025 priorities
In the third quarter of 2025, our priorities are:

* Implementing [C++23 features](https://github.com/orgs/microsoft/projects/1142/views/2) and [LWG issues](https://github.com/orgs/microsoft/projects/1152/views/2) from the Working Draft
  + `feature/flat_map` is the multi-collaborator feature branch for both #2910 and #2912
* We're expecting to accept contributions for [C++26 features](https://github.com/orgs/microsoft/projects/1143/views/2) after finishing the C++23 library-only features
* Keeping PR reviews flowing, so contributions are reviewed promptly

If you have questions about our plans for this quarter, feel free to ask them here. (Note that compiler, IDE, etc. priorities are off-topic.)

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Fix #4553

Add coverage, so that the test would fail without the fix.

### CODE REVIEW

**Comment by jovibor** [comment]
Wrong Fix.
Must be #4553.

**Comment by AlexGuteniev** [comment]
> Wrong Fix. Must be #4553.

Fixed Fix.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
:warning: Note to self: This should be changelogged as fixing a regression.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for noticing and fixing this bug, when I had forgotten that my old `find` `memchr` fix was relevant here! :lady_beetle: :hammer_and_wrench: :tada:

**Pull request merged**
