### PR TITLE
lerp() noexcept is now required, so we should remove comments

### LINKED ISSUE #530: <cmath>: lerp() noexcept is now required, so we should remove comments
Background: The Standard requires various functions to be marked `noexcept`, and additionally permits implementers to "strengthen" other functions of their choice by adding `noexcept`.

When our former intern Paolo Torres implemented `lerp()` in VS 2019 16.3, he noticed that `noexcept` was missing from its specification. He filed a Library Issue (bug report against the C++ Standard) LWG-3201 "`lerp` should be marked as `noexcept`", and he also strengthened his implementation. We follow a convention of marking such occurrences with comments:

https://github.com/microsoft/STL/blob/e03429600efd951791ba4a903b449fac7473bef9/stl/inc/cmath#L1387-L1400

After the February 2020 meeting in Prague, Paolo's resolution for LWG-3201 has been accepted, so the C++20 Standard has caught up to his implementation (yay!). Accordingly, we should remove the `/* strengthened */` comments on these overloads (as `noexcept` is required now).

### PR DESCRIPTION
**Pull request by dtoma**
Description
===========

Remove `/* strengthened*/` comments now that `noexcept` is required by the standard.

Fixes #530 

Checklist
=========

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

**Comment by dtoma** [comment]
Thanks for the very detailed comment! In this kind of case, do you prefer amending/force pushing the commit, or adding a new commit with the fixed formatting?

**Comment by StephanTLavavej** [comment]
Thanks for asking! Adding a new commit makes reviewing easier, since GitHub provides UI to see "changes since your last review". When we merge pull requests, we choose to squash each PR into a single commit for tidy linear history, so it won't affect what goes into the repo history.

**Comment by CaseyCarter** [comment]
@dtoma FYI I've merged master into your branch to resolve a merge conflict with #645.

**Comment by dtoma** [comment]
Thanks! Should I run clang-format 10.0 from now on?

**Comment by CaseyCarter** [comment]
> Thanks! Should I run clang-format 10.0 from now on?

Yes - clang-format 10 is now the gold standard.

**Comment by cbezault** [comment]
Thanks for the contribution!

**Pull request merged**
