### PR TITLE
Alternative way to optimize `_Countr_zero`

### LINKED ISSUE #2292: `<numeric>`: `_Countr_zero` used by `std::gcd` has unnecessary zero checks
Originally reported as DevCom-1560717

`_Countr_zero` in this loop has unnecessary checks for zero input in the compiled code:

https://github.com/microsoft/STL/blob/d8f03cf399d730780b6ca0e5321a9ff4fc76bb0f/stl/inc/numeric#L567-L577

See the demo with `__assume` workaround: https://godbolt.org/z/Ts7ExjbYb

As the reported noted, compiler codegen could be improved.

But from the library, it can also be fixed by making specialized `_Countr_zero` that does not check for zero input, and calling the specialized version from `std::gcd`.

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Do stuff like _Select_popcount_impl.

Resolves #2292 a bit more efficient than #2298

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I created conflicts by changing #2337 for `/clr:pure` compatibility, so I'll resolve them here. One moment...

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I've pushed a merge with `main` to resolve a simple conflict in `<numeric>` (where clang-format 13 had removed a space). I diffed `<numeric>` before and after this merge, and there are no changes to this PR's content except for the clang-format changes.

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for improving the performance of this function with clear, maintainable code! :rocket: :tada: :heart_eyes_cat:

**Pull request merged**
