### PR TITLE
<yvals_core.h>: Update _MSVC_STL_UPDATE to July 2022

### LINKED ISSUE #2836: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to July 2022
Explanation on our wiki: [Macro _MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code: https://github.com/microsoft/STL/blob/c34f24920e463a71791c2ee3d2bed14926518965/stl/inc/yvals_core.h#L615

Previous issue: #2752

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by Alikhalesi**
Resolves #2836

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Review by fsb4000 — APPROVED** [review]
Congratulations for your first contribution 🎉

**Review by strega-nil-ms — APPROVED** [review]
Thank you for the PR! :heart:

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! This will ship in VS 2022 17.4 Preview 2. :tada: :smile_cat: :rocket:

**Pull request merged**
