### PR TITLE
Add error_code, error_category support to visualizer

### PR DESCRIPTION
**Pull request by cmazakas**
This PR aims to implement the requested fixes outlined in https://github.com/microsoft/STL/pull/3044/files

In general, I prefer the approach of requiring function evaluation as it helps keep the visualizer code layout-independent.

Let me know if there's anything to be changed!

### CODE REVIEW

**Comment by cmazakas** [comment]
@microsoft-github-policy-service agree

**Review by StephanTLavavej — APPROVED** [review]
This looks reasonable to me (although I have not tested it in the debugger). Thanks!

**Comment by strega-nil-ms** [comment]
I'll take a look at this tomorrow in the debugger.

**Review by strega-nil-ms — CHANGES_REQUESTED** [review]
So, this is how `error_code` looks:

```
{ value=0, category=[???] }
```

and if you click the little circle-y thing, you get

```
{ value=0, category=[system] }
```

For `error_condition`, instead you get:

```
{_Myval=2 _Mycat=0x00007ff60b389008 {OptionalDebuggerIssues.exe!std::_Generic_error_category _Static} [generic] }
```

which seems like the `name()` call doesn't work; what's going on here? am I missing something?

**Comment by cmazakas** [comment]
Huh, `error_condtion`?

I was using the test template that was suggested in the other PR so I wound up using this:
```cpp
#include <future>
#include <ios>
#include <string>
#include <system_error>

struct my_error_category : public std::error_category {
	const char* name() const noexcept override {
		return "potato";
	}

	std::string message(int) const override {
		return "message goes here";
	}
};

int main() {
	auto& generic_cat = std::generic_category();
	auto& system_cat = std::system_category();
	auto& iostream_cat = std::iostream_category();
	auto& future_cat = std::future_category();
	const auto& my_cat = my_error_category();

	std::error_code generic(42, generic_cat);
	std::error_code system(42, system_cat);
	std::error_code iostream(42, iostream_cat);
	std::error_code future(42, future_cat);
	std::error_code my(42, my_cat);
}
```

On my install of VS, this winds up looking like this:
Screenshot_20221202_121423

Enabling functions calls in value formatting winds up looking like this: 
Screenshot_20221202_121720

So I don't think I'm replicating what you're seeing. Would you mind sharing your code/some screenshots so I have a better idea of what's going on?

**Comment by strega-nil-ms** [comment]
I misunderstood! I misread `error_category` as `error_condition` somehow; this _does_ seem reasonable to me, then, although I don't know how comfortable people generally are with function calls in visualizers...

**Review by strega-nil-ms — APPROVED** [review]

**Pull request merged**
