### PR TITLE
Adopt LWG-3390

### LINKED ISSUE #547: LWG-3390 `make_move_iterator()` cannot be used to construct a `move_iterator` for a move-only iterator
LWG-3390 `make_move_iterator()` cannot be used to construct a `move_iterator` for a move-only iterator

### PR DESCRIPTION
**Pull request by Svido**
Fixes #547

# Description
Adopting LWG-3390.

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Can you add tests for this?

**Comment by Svido** [comment]
> Can you add tests for this?
Sure.  Where is the best place to add the tests?

**Comment by BillyONeal** [comment]
> > Can you add tests for this?
> > Sure.  Where is the best place to add the tests?

Normally:

1. grep somewhere in tests/std for a test already testing close to what you're testing and insert into there where it makes sense
2. if there are no good candidates, add a new test by:
    * creating a new directory tests/std/tests/(name your test here)
    * put an `env.lst` in there indicating the configurations you support, in this case probably an identical copy of https://github.com/microsoft/STL/blob/master/tests/std/tests/P0595R2_is_constant_evaluated/env.lst
    * put a `test.cpp` in that directory that `assert()`s or `static_assert()`s what you want
    * add your new directory to `tests/std/test.lst`

**Comment by StephanTLavavej** [comment]
Thanks again! Now we're closer to zero LWG issues remaining :-)

**Pull request merged**
