### PR TITLE
add explicit non-zero context to `_Countr_zero`

### LINKED ISSUE #2292: `<numeric>`: `_Countr_zero` used by `std::gcd` has unnecessary zero checks
Originally reported as DevCom-1560717

`_Countr_zero` in this loop has unnecessary checks for zero input in the compiled code:

https://github.com/microsoft/STL/blob/d8f03cf399d730780b6ca0e5321a9ff4fc76bb0f/stl/inc/numeric#L567-L577

See the demo with `__assume` workaround: https://godbolt.org/z/Ts7ExjbYb

As the reported noted, compiler codegen could be improved.

But from the library, it can also be fixed by making specialized `_Countr_zero` that does not check for zero input, and calling the specialized version from `std::gcd`.

### PR DESCRIPTION
**Pull request by AlexGuteniev**
fixes #2292

x86 diff:
https://godbolt.org/z/v7v9zv3Gr
x64 diff:
https://godbolt.org/z/b8h86MrMo

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
@AlexGuteniev I have pushed a merge with `main`, containing **major** changes to `<limits>`. I believe that this preserves the intent of your changes, while applying them to the post-#2333 codebase, refactoring the logic to be cleaner (particularly around the widen-8/16-bits logic), and further enhances the nonzero optimization (in particular, we can avoid inspecting BSF's return value).

Please let me know if anything looks weird/wrong!

**Comment by AlexGuteniev** [comment]
> Please let me know if anything looks weird/wrong!

I think it is correct, but looks like without attempting to use `tzcnt` as `bsf` the intent may need reconsideration.

As the change was originally written, it avoided branches. The branches were there only for zero input.
Now there is a branch between `tzcnt` and `bsf`, regardless of zero/nonzero. And `bsf` itself is branchless (it uses `cmov`).
And `bsf` is a fallback.

So currently the change appears to be near-zero improvement, that doesn't even worth complicating code.

Need to benchmark and inspect codegen to figure out what should be done. Maybe implementing the same thing as for `vector<👻>`. Maybe just implementing #2133 will do (then again, this change may be useful, but may be not).

**Comment by AlexGuteniev** [comment]
This optimization makes gcd 1 to 2 percent faster.
I've tried alternative approach (similar to `_Select_popcount_impl`), it turned out to be slightly faster than this one, still between 1 and 2 percent faster than the current.
Do we want to proceed?

**Comment by StephanTLavavej** [comment]
1-2% is worth it, I think (it's pretty small on the scale of libs performance improvements, but it's easily something that the backend team would celebrate as their codegen is already highly optimized, and improving program perf without user-programmer intervention is always nice). @barcharcraz agrees - let's proceed!

**Comment by AlexGuteniev** [comment]
Please consider submitting #2343 instead of this one. 
It:
 * Gives slightly better results
 * Easier to explain the optimization
 * Consistent with similar optimization for `_Popcount`

**Comment by StephanTLavavej** [comment]
Looking at #2343, I agree that it appears to be superior. Closing this PR.

**Pull request closed without merging**
