### PR TITLE
`vector_algorithms.cpp`: clearer control flow in `bitset::to_string`

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Use `else` instead of early return

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Is this clearer? I need to think about whether the finality of an early `return` is better than chaining.

**Comment by AlexGuteniev** [comment]
It now stands out so that it is clear that it is only a fallbaxk, and not tail handling

**Comment by jovibor** [comment]
Honestly, it's more of a personal preference than anything.
Also, this construct:
```cpp
    } else
#endif // !defined(_M_ARM64EC)
```
looks clunky. (`else` immediately following by `endif`)

**Comment by StephanTLavavej** [comment]
@AlexGuteniev Hmm, I suppose it's at least equally clear.

@jovibor It looks weird, but we've increasingly used this pattern when we need to interleave preprocessor conditions with `if constexpr` or runtime `if` control flow. I have to imagine both preprocessor situations in sequence when reasoning about such code, but as long as the interleaving isn't too tangled, it ends up being reasonably readable.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
:broom: :eyeglasses: :sparkles:
===

**Pull request merged**
