### PR TITLE
Fix issue-218 - remove public redundancy

### PR DESCRIPTION
**Pull request by lozinska**
# Checklist

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] I understand README.md. I also understand that acceptance of
  community PRs will be delayed until the test and CI systems are online.
- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before CI is online, leave this unchecked for
  initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository and
  the C++ Working Draft as a reference (and any other cited standards).
  If they were derived from a project that's already listed in NOTICE.txt,
  that's fine, but please mention it. If they were derived from any other
  project (including Boost and libc++, which are not yet listed in
  NOTICE.txt), you *must* mention it here, so we can determine whether the
  license is compatible and what else needs to be done.

### CODE REVIEW

**Comment by lozinska** [comment]
Thank you. I will fix it

**Comment by StephanTLavavej** [comment]
Thank you, and congratulations for your first merged commit!

**Comment by BillyONeal** [comment]
info  run completed in 00:06:44.4094864: 21695 passed, 0 failed

Thanks!

**Pull request merged**
