### PR TITLE
Reorganize included headers for improved readability

### PR DESCRIPTION
**Pull request by Alik-Agarwala**
This commit reorganizes the included headers in the code for enhanced readability. The system headers are now grouped together at the top. This grouping distinguishes them as external dependencies. The local header file, "awint.hpp", follows, indicating its relationship as a project-specific file.

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
Clang-format doesn't like the change.

I'm neutral on deleting the empty line itself, but I don't think I like turning off/on Clang-format for this.

**Comment by CaseyCarter** [comment]
I agree that there's not enough benefit here to suppress autoformatting. I do think we'd be willing to entertain a change to the `#include`-ordering rules in `.clang-format` that accomplished the same thing, however.

**Comment by StephanTLavavej** [comment]
I don't believe that we should do anything here, including modifying `.clang-format`. We are intentionally putting `<Windows.h>` in a separate clang-format group. Removing the empty line doesn't enhance clarity in my opinion.

(There are other files where we are manually controlling header order due to improper design of Windows SDK headers, and teaching clang-format to do that automatically would be valuable. That isn't the case in this file, though.)

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting and have concluded that this isn't a direction we want to proceed in. Thanks again for submitting this PR.

**Pull request closed without merging**
