### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by cbezault**
DO NOT MERGE TEST PR

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
I assume we'll need to merge `master` to `feature/spaceship` before this can succeed; I'll prepare a PR after we get a successful CI run.

**Comment by cbezault** [comment]
This should just work :/

**Comment by cbezault** [comment]
I think we should add a "update the default pipeline" step to the updating the VMs portion of the Wiki. It appears attempting to update a setting in the YAML page of ADO, such as changing the branches which trigger a PR test, causes the setting to become required.

**Comment by CaseyCarter** [comment]
> I think we should add a "update the default pipeline" step to the updating the VMs portion of the Wiki. It appears attempting to update a setting in the YAML page of ADO, such as changing the branches which trigger a PR test, causes the setting to become required.

I can live with that, but I can't help but wonder how this design is supposed to scale to projects with more than one defined pipeline. Should we be defining triggers in the YAML instead of via the UI?

**Comment by cbezault** [comment]
I wouldn't want people to be able to trigger pipelines by making PRs from a fork which modify the triggers in the YAML.

**Comment by StephanTLavavej** [comment]
Can this be closed now? `feature/spaceship` CI appears to be working.

**Pull request closed without merging**
