### PR TITLE
Wait `condition_variable_any` for `steady_clock`

### LINKED ISSUE #4723: `<condition_variable>`: `condition_variable_any::wait_for` returns `cv_status::timeout` when the elapsed time is shorter than requested
# Describe the bug
Revealed by libc++ test [`test/std/thread/thread.condition/thread.condition.condvarany/wait_for.pass.cpp`](https://github.com/llvm/llvm-project/blob/e9a362362e03c6aea7a64473e8b8bb9140fd3855/libcxx/test/std/thread/thread.condition/thread.condition.condvarany/wait_for.pass.cpp).

[\[thread.condvarany.wait\]/13](http://eel.is/c++draft/thread.condvarany.wait#13):
> Returns: `cv_status​::​timeout` if the relative timeout ([thread.req.timing]) specified by `rel_time` expired, otherwise `cv_status​::​no_timeout`.

But MSVC STL's `condition_variable_any::wait_for` sometimes returns `cv_status​::​timeout` even though the elapsed time (measured by `high_resolution_clock`) is shorter than the requested timeout.

# Command-line test case
```
D:\test>type test-condvarany.cpp
#include <condition_variable>
#include <atomic>
#include <cassert>
#include <chrono>
#include <mutex>
#include <thread>
#include <print>

template <class Mutex>
struct MyLock : std::unique_lock<Mutex> {
  using std::unique_lock<Mutex>::unique_lock;
};

template <class Function>
std::chrono::microseconds measure(Function f) {
  std::chrono::high_resolution_clock::time_point start = std::chrono::high_resolution_clock::now();
  f();
  std::chrono::high_resolution_clock::time_point end = std::chrono::high_resolution_clock::now();
  return std::chrono::duration_cast<std::chrono::microseconds>(end - start);
}

template <class Lock>
void test() {
  using Mutex = typename Lock::mutex_type;

  // Test unblocking via a timeout.
  //
  // To test this, we create a thread that waits on a condition variable
  // with a certain timeout, and we never awaken it. To guard against
  // spurious wakeups, we wait again whenever we are awoken for a reason
  // other than a timeout.
  {
    auto timeout = std::chrono::milliseconds(250);
    std::condition_variable_any cv;
    Mutex mutex;

    std::thread t1([&] {
      Lock lock(mutex);
      std::cv_status result;
      do {
        auto elapsed = measure([&] { result = cv.wait_for(lock, timeout); });
        if (result == std::cv_status::timeout)
          if (elapsed < timeout) {
            std::println("elapsed: {}", elapsed);
            std::println("timeout: {}", timeout);
          }

      } while (result != std::cv_status::timeout);
    });

    t1.join();
  }
}

int main(int, char**) {
  test<std::unique_lock<std::mutex>>();
  test<std::unique_lock<std::timed_mutex>>();
  test<MyLock<std::mutex>>();
  test<MyLock<std::timed_mutex>>();
  return 0;
}

D:\test>cl /EHs /std:c++latest test-condvarany.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.41.33901 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

test-condvarany.cpp
Microsoft (R) Incremental Linker Version 14.41.33901.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test-condvarany.exe
test-condvarany.obj

D:\test>.\test-condvarany.exe
elapsed: 249758us
timeout: 250ms
```

(You might need to execute the program several times to see the output.)

# Expected behavior
`.\test-condvarany.exe` should consistently produce no output

# STL version

    v17.11.0-pre.1.0

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Fixes #4723

Turned out that:
 * WinAPI `SleepConditionVariableSRW` times out using a steady clock that is not precisely synchronized with `steady_clock` implemented based on `QueryPerformanceCounter`
 * Fixing it with `GetTickCount64()` check doesn't help, as `GetTickCount64()` is also not precisely synchronized with `QueryPerformanceCounter`

The fix is to check exactly `steady_clock` in `condition_variable_any`.

This is done in a header, rather than in `.cpp` for these reasons:
 * The header implementation of `steady_clock::now()` is nontrivial, and resides in a non-core header, and we don't have a good core header to extract it into
 * Other call sites of the internal condition variable wait function check against the clock on their own already

That's why `GetTickCount64()` was removed from internal wait function.

To avoid destabilizing behavior for already compiled code, I kept `GetTickCount64()` on that code path (it might improve over raw `SleepConditionVariableSRW` a bit).

I've inlined `_Wait_for_ms_count` as to me it appeared clearer this way after these changes.

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! I pushed a conflict-free merge with `main` and a simple transformation. This fix makes sense and I verified that the affected libcxx tests pass 10 times in a row. :heart_eyes_cat:

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this long-standing sporadic bug! :hourglass_flowing_sand: :lady_beetle: :heart_eyes_cat:

**Comment by NipaJ** [comment]
`_Cnd_timedwait_for_unchecked` is missing `_CRTIMP2_PURE`, forcing static linkage always. This is problematic, since the function is missing from the DLL version of the runtime library.

**Comment by StephanTLavavej** [comment]
By design: https://github.com/microsoft/STL/pull/4457#issuecomment-2941202955

**Pull request merged**
