### PR TITLE
updated _MSVC_STL_UPDATE

### LINKED ISSUE #2515: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to February 2022
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/b11945b73fc1139d3cf1115907717813930cedbf/stl/inc/yvals_core.h#L585

Previous issue: #2454

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### PR DESCRIPTION
**Pull request by ritik307**
Fixes #2515

### CODE REVIEW

**Comment by ritik307** [comment]
Hi, @StephanTLavavej Made a PR. Kindly review 😊

**Review by cpplearner — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Review by fsb4000 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by ritik307** [comment]
@StephanTLavavej Nothing to push 😊

**Review by ddr533 — APPROVED** [review]

**Comment by ddr533** [comment]
Excellent work!

**Pull request merged**
