### PR TITLE
Fix `ambiguous_local_time`'s message is slightly incorrect 

### LINKED ISSUE #3648: `<chrono>`: `ambiguous_local_time`'s message is slightly incorrect
## Bug description

The message of `ambiguous_local_time` exception class should be (per [[time.zone.exception.ambig]/4](http://eel.is/c++draft/time.zone.exception#ambig-3)):

> *Effects*: Initializes the base class with a sequence of `char` equivalent to that produced by `os.str()` initialized as shown below:
> ```c++
> ostringstream os;
> os << tp << " is ambiguous.  It could be\n"
>    << tp << ' ' << i.first.abbrev << " == "
>    << tp - i.first.offset << " UTC or\n"
>    << tp << ' ' << i.second.abbrev  << " == "
>    << tp - i.second.offset  << " UTC";
> ```

Repro:

```c++
#include <cassert>
#include <chrono>
#include <iostream>
#include <string>

int main() {
  const std::string_view required_start =
      "2016-11-06 01:30:00 is ambiguous.  It could be";

  // Example 1, [time.zone.exception.ambig]/4
  using namespace std::chrono;
  try {
    auto zt = zoned_time{"America/New_York",
                         local_days{Sunday[1] / November / 2016} + 1h + 30min};
  } catch (const ambiguous_local_time &e) {
    std::cout << e.what() << '\n';
    assert(std::string_view{e.what()}.starts_with(required_start));
  }
}
```

Build:

```console
PS D:\stl-playground> clang -std=c++20 .\test.cpp
PS D:\stl-playground> .\a.exe
2016-11-06 01:30:00 is ambiguous. It could be
2016-11-06 01:30:00 GMT-4 == 2016-11-06 05:30:00 UTC or
2016-11-06 01:30:00 GMT-5 == 2016-11-06 06:30:00 UTC   
Assertion failed: std::string_view{e.what()}.starts_with(required_start), file .\test.cpp, line 17
```

Summary:
* There is one extra space (`0x20`) missing between *"ambiguous."* and *"It"*,
* Compiler explorer (GCC): https://godbolt.org/z/E36xP4x3z.

## "Good first issue" tips

It should say *`is ambiguous.  It could be`* (two spaces) in those places:
* https://github.com/microsoft/STL/blob/e6a12f7e12306cf0d6f256f70777e0107993feec/stl/inc/chrono#L6014
* https://github.com/microsoft/STL/blob/e6a12f7e12306cf0d6f256f70777e0107993feec/tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp#L801
* https://github.com/microsoft/STL/blob/e6a12f7e12306cf0d6f256f70777e0107993feec/tests/std/tests/P0355R7_calendars_and_time_zones_formatting/test.cpp#L805

### PR DESCRIPTION
**Pull request by YairBorn**
Fixed #3648.

### CODE REVIEW

**Comment by YairBorn** [comment]
> 
@microsoft-github-policy-service agree

**Comment by YairBorn** [comment]
> @YairBorn please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement
@microsoft-github-policy-service agree

**Comment by YairBorn** [comment]
@microsoft-github-policy-service agree

**Review by StephanTLavavej — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for contributing to the expansion of the universe as the space between sentences grows! :joy_cat: :flying_saucer: :ringed_planet:

**Pull request merged**
