### PR TITLE
[vNext] Modernize array iterators

### PR DESCRIPTION
**Pull request by miscco**
Renewal of the iterator machinery has been a repeated topic for the vNext branch.

This follows the recent approach by the ranges views machinery and passes an additional boolean around to signify whether it is a const_iterator or not.

Usually it would be a private sub class of the respective container, but thanks to every ones favorite `array<_Ty, 0>` this is not possible here.

This is more a RFC whether this is the right approach and whether it makes sense for the other containers.

Also this adds `_Begin` and `_End` pointer for iterator debug which would increase memory consumption but enableoverflow checks

### CODE REVIEW

**Comment by AdamBucior** [comment]
Since you removed all use cases of `_Size` in array's iterator you can remove this template parameter and fix #211.

**Comment by miscco** [comment]
@AdamBucior, thanks for remembering that discussion ;)

As this is more of a RFC than an actual PR I would wait until there is actual work on vNext to integrate those changes

**Comment by miscco** [comment]
Who am I kidding. Removed the unneeded `_Size` template parameter

**Comment by MikeGitb** [comment]
Has there been any discussion about putting the common parts for all continuous range iterators (std::vector, array, span, maybe even string_view) into a common (base-?) class? My hope would be that this would increase compilation throughput (just a hope, no idea if it would) and reduce the maintenence overhead due to having less code.

I feel like I have suggested  that before and already received an answer, but can't find the issue at the moment.

**Comment by miscco** [comment]
I believe that most iterators are intricately linked to their container, so that this would not be easily done.

For example look at the iterator debugging machinery. Just list, vector, and array are widely different

**Comment by MikeGitb** [comment]
Sorry for the noise then. I expected the iterators to be essentially wrappers around a single pointer in release mode and three pointers (start, current position, end) in debug mode.

**Comment by StephanTLavavej** [comment]
I already overhauled array's iterators in the old "WCFB02" vNext branch, starting with:

```cpp
template<class _Ty,
	size_t _Size,
	bool _Constant,
	bool _Checked>
	class _Array_iter
```

This used the same "template on constness" technique you mentioned, which I used in the other container iterators. I don't know if my 3-year-old changes were ideal; when we extract them from the old branch, we should compare them against what you've done here. (Note that until we finish C++20, we won't really have the bandwidth to review or offer detailed thoughts about vNext changes.)

Most of the overhaul work went into centralizing and improving the iterator chaining used by all non-array iterators; templating them on constness and checkedness was done at the same time. The iterators that I didn't get around to were `deque` and `vector<bool>`. For `deque`, we will need to explore a different representation that doesn't need a proxy.

**Comment by StephanTLavavej** [comment]
Closing this PR as I've provided comments above - please wait until we start the vNext branch and salvage the old iterator overhaul, then we'll happily review further refinements/overhauls.

**Pull request closed without merging**
