### PR TITLE
<yvals_core.h> Update _MSVC_STL_UPDATE to #define _MSVC_STL_UPDATE  202208L

### LINKED ISSUE #2836: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to July 2022
Explanation on our wiki: [Macro _MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code: https://github.com/microsoft/STL/blob/c34f24920e463a71791c2ee3d2bed14926518965/stl/inc/yvals_core.h#L615

Previous issue: #2752

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### LINKED ISSUE #2979: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to August 2022
Explanation on our wiki: [Macro _MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code: https://github.com/microsoft/STL/blob/b7e0365b5e2f9de738e8fbea42b6cc6880efe531/stl/inc/yvals_core.h#L618

Previous issue: #2836

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by lantastic99**
Fixes #2979

### CODE REVIEW

**Review by JMazurkiewicz — APPROVED** [review]

**Comment by JMazurkiewicz** [comment]
PR description has wrong issue number (should be `#2979`).

**Comment by frederick-vs-ja** [comment]
Note that this PR is fixing `#2873`, `#2940`, and `#2979`. The description should use "Fixes _, fixes _, fixes _." to fix each of them.

**Review by fsb4000 — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]
Thank you so much! This looks great :)

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Review by frederick-vs-ja — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! :tada: :heart_eyes_cat: :rocket:

**Pull request merged**
