### PR TITLE
Add check-spelling/check-spelling

### PR DESCRIPTION
**Pull request by jsoref**
## Automatically check spelling
This adds the [check-spelling](https://github.com/marketplace/actions/check-spelling) GitHub action which I used to develop #743.

### Annotations / Comments
The action generates annotations for commits such as:
annotation identifying misspelled word

https://github.com/microsoft/terminal/pull/5501/commits/1cdb390a0b11cbb071beca45fb1190ef4fd774b6#diff-1de1db347c9d77a9474a6e98cf675d69R176

Along with comments:
comment identifying a new misspelling

### Configuration
Configuration is contained within `.github/actions/spell-check/`.

#### Exclusions
If you decide that tests don't need to be checked, you can edit `.github/actions/spell-check/excludes.txt` to add:
```
^tests/
```

#### Advice
You can add [advice.txt](https://github.com/microsoft/terminal/blob/master/.github/actions/spell-check/advice.txt) to include customized suggestions.

---
@CaseyCarter @cbezault @StephanTLavavej

### CODE REVIEW

**Comment by cbezault** [comment]
How did you produce that whitelist?

**Comment by jsoref** [comment]
Manually. The tool reports everything it doesn't recognize, and I look at things and decide "probably ok", or "let me check". (It's definitely possible there are things in the list that shouldn't be whitelisted.)

As users add things that need to be whitelisted, the tool will suggest a command to add things into the whitelist.

For the example above, if you believed that the spelling was correct,
https://github.com/microsoft/terminal/commit/1cdb390a0b11cbb071beca45fb1190ef4fd774b6#commitcomment-38699049 -- click to expand the comment, click `To accept these changes, run the following commands`:
feedback with instructions for updating the whitelist

The easiest way to experience this is to take a fork of this branch, add a commit w/ a misspelling and push. You don't need to create a PR as the action responds to pushes -- the idea being that you want feedback *before* you make the PR w/ the misspelling.

**Comment by StephanTLavavej** [comment]
Thanks for the PR. I'm unsure whether maintaining this automation, and dealing with false positives, is worth the time cost. We tend to be pretty careful about spelling in code reviews (as evidenced by the very low number of spelling mistakes found in the previous cleansing - those escaped my previous grepping and manual reading of all comments).

I'll see what the other maintainers think. If we were to accept this, the file of allowed words would need to be renamed; "allowlist", "allowedlist", etc. would be fine.

**Comment by jsoref** [comment]
Thanks for the feedback.

Adding that shouldn't be a problem -- I can add for the next release.

---
Right now, [microsoft/terminal](https://github.com/microsoft/terminal) uses a custom dictionary which means that when people use a word that was technically a word, but not actually the intended word, they remove it from the dictionary so that it can be caught in the future: 

* [wether](https://github.com/microsoft/terminal/commit/9409e851d043775ea973a7cc50cc1ba0c2f660a2#diff-4a97f7b6bd038d5e4082fe476036b224)
* [spae](https://github.com/microsoft/terminal/commit/dc43524eb23feb9962e5277c639628d0e982f1bf#diff-4a97f7b6bd038d5e4082fe476036b224)

Here's an example of a line which indeed uses a word, but, it's just, not the right word:
https://github.com/grafana/grafana/blob/55ac97dccceb69ace8113f0c62a39aa6b94aec9f/e2e/suite1/specs/panelEdit_queries.spec.ts#L8

People suggested that I offer a delta file that would enable one to do so w/o committing a dictionary into the repository, I had tentatively used the color opposite of `allowlist`. Would you suggest that I name such a list `rejectlist`? (I'm really shopping for names for this feature, and really all of my features -- my goal is to enable smooth adoption of the action...)

**Comment by CaseyCarter** [comment]
> Thanks for the PR. I'm unsure whether maintaining this automation, and dealing with false positives, is worth the time cost.

I'm similarly wary - I can imagine this turning into a timesink. That said, the barrier for entry is low and I believe we could yank this easily if and when we determine that it doesn't meet our needs.

> Would you suggest that I name such a list `reject`?

I believe "denylist" is the commonly accepted complement of "allowlist."

**Comment by jsoref** [comment]
I went with `expect` as the tool does want to prune out things that are no longer present (things that can come and go should be moved into the dictionary).

With 0.0.16 you can now both supplement (`allow`) and remove (`reject`) from the dictionary without outright replacing it (`dictionary`). And you can easily limit scanning (`only`) instead of merely `exclude`-ing files.

**Comment by StephanTLavavej** [comment]
Thanks again for the PR. After talking with the other maintainers, we've decided not to merge this. For our particular repo, which is relatively small and undergoes intensive code review, noticing and fixing spelling errors isn't a significant time sink. Not a criticism of your GitHub Action, which is a great fit for many other repos!

**Comment by jsoref** [comment]
Thanks for the consideration and feedback - it did help improve the tool.

**Pull request closed without merging**
