### PR TITLE
Improve `search`/`find_end` perf by dropping `memcmp`

### LINKED ISSUE #2453: `<algorithm>`: vectorize `search`
The following example:

```C++
#include <chrono>
#include <cstring>
#include <iostream>
#include <functional>
#include <random>
#include <search.h>
#include <string>

const std::string haystack =
R"(Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit quam vel dui scelerisque vehicula. Suspendisse ipsum felis,
    mattis vitae tortor at, rutrum semper nibh. Suspendisse dui ante, maximus sit amet lorem in, tempor ornare massa. Sed eget interdum mauris.
    Vivamus iaculis ante odio, quis gravida libero aliquet ut. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
    Fusce egestas, felis et sagittis luctus, nisl lacus pretium tortor, sed vestibulum arcu odio nec dolor. Quisque scelerisque diam ac facilisis placerat.
    Cras et ante non nunc ornare ultricies. Pellentesque in feugiat nibh. Etiam tincidunt finibus pharetra. Proin ornare mollis elit, in pretium turpis.
    Aenean pharetra ipsum enim, ultrices iaculis odio interdum eget. Proin ullamcorper ullamcorper eros, ullamcorper condimentum dolor rhoncus eget.
    Fusce ligula velit, posuere quis fermentum id, faucibus ac ipsum.

    Aliquam quis metus eget neque vestibulum malesuada. Suspendisse et fermentum turpis. Phasellus egestas metus quis lacinia pellentesque. Orci varius
    natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In fringilla justo vitae massa laoreet rutrum. Donec accumsan sem velit,
    quis fermentum mi egestas sit amet. Suspendisse potenti. Vestibulum semper lacinia urna volutpat laoreet. Vestibulum scelerisque libero nunc, vitae
    tincidunt nulla accumsan id. Sed non nisl nec nisi varius viverra nec consectetur augue. Duis lectus eros, mollis eget lectus eget, euismod bibendum
    tortor. Ut pharetra euismod metus.

    Morbi suscipit urna turpis, nec blandit lacus lobortis a. Donec purus nunc, elementum sit amet massa ac, dapibus pharetra enim. Mauris bibendum tempor
    orci rutrum auctor. Donec sed maximus erat, porttitor interdum sapien. Donec at est id nunc pulvinar molestie. Praesent sed facilisis orci, a congue
    tellus. Nulla venenatis at dolor vitae sagittis. Morbi eget dapibus diam. Ut a eros eros. Cras at augue tortor. Nam ac dictum leo, eget placerat urna.
    Etiam non elit vel neque efficitur bibendum in nec nisi. Maecenas massa mi, placerat in efficitur vel, vehicula non nisi. Pellentesque vitae est velit.

    Nam faucibus nibh ex, vitae fringilla odio dignissim eu. Curabitur eu dui at lectus luctus auctor sit amet sed quam. Nam volutpat, nunc dignissim
    posuere aliquam, dui diam tristique quam, at mollis ex urna in nunc. Donec in dui gravida, varius elit vel, facilisis felis. Vivamus diam enim, commodo
    eget porta ac, aliquet at justo. Duis in augue ac ligula malesuada vehicula eget euismod ipsum. Quisque placerat est sit amet ante elementum,
    quis laoreet est auctor.

    Morbi eleifend gravida dui quis dignissim. Integer sit amet iaculis turpis. Duis metus urna, imperdiet at auctor eget, lacinia sagittis magna.
    Ut vestibulum justo at purus egestas, vitae gravida dui semper. Integer mattis facilisis pulvinar. Mauris vitae finibus nunc. In lacinia hendrerit diam,
    et egestas tellus imperdiet quis. In vulputate fringilla tellus nec blandit. Cras dictum consequat neque, nec laoreet nibh dictum et. Praesent venenatis
    enim sed rhoncus elementum. Nunc in magna in erat pretium volutpat aliquet eget purus. Maecenas porttitor velit a hendrerit dignissim. Mauris ullamcorper
    mauris et magna aliquet fermentum. Ut imperdiet porta erat.)";

const std::string needle = "sed quam";

const void* volatile discard;

int main()
{
    constexpr int N = 1'000'000;

    auto t1 = std::chrono::steady_clock::now();
    for (int i = 0; i < N; ++i) {
        discard = std::strstr(haystack.c_str(), needle.c_str());
    }
    auto t2 = std::chrono::steady_clock::now();
    std::default_searcher s1{ needle.begin(), needle.end() };
    for (int i = 0; i < N; ++i) {
        discard = &*std::search(haystack.begin(), haystack.end(), s1);
    }
    auto t3 = std::chrono::steady_clock::now();
    std::boyer_moore_searcher s2{ needle.begin(), needle.end() };
    for (int i = 0; i < N; ++i) {
        discard = &*std::search(haystack.begin(), haystack.end(), s2);
    }
    auto t4 = std::chrono::steady_clock::now();
    std::boyer_moore_horspool_searcher s3{ needle.begin(), needle.end() };
    for (int i = 0; i < N; ++i) {
        discard = &*std::search(haystack.begin(), haystack.end(), s3);
    }
    auto t5 = std::chrono::steady_clock::now();

    std::cout
        << "strstr  " << std::chrono::duration_cast<std::chrono::duration<double>>(t2 - t1) << "\n"
        << "default " << std::chrono::duration_cast<std::chrono::duration<double>>(t3 - t2) << "\n"
        << "BM      " << std::chrono::duration_cast<std::chrono::duration<double>>(t4 - t3) << "\n"
        << "BMH     " << std::chrono::duration_cast<std::chrono::duration<double>>(t5 - t4) << "\n";
}
```

The results are:
```
strstr  0.199604s
default 3.08794s
BM      1.19609s
BMH     1.17713s
```

The default algorithm does not have any requirements on how it should be implemented, so it could be vectorized.

BM and BMH should stay as is, they show benefit on larger data (like some kilobytes substring)

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Resolves #2453

<details>
<summary>These benchmark results are no longer relevant, as the PR intention has changed</summary>

Before:
```
---------------------------------------------------------------------------------
Benchmark                                       Time             CPU   Iterations
---------------------------------------------------------------------------------
c_strstr                                      184 ns          119 ns      8960000
ranges_search<std::uint8_t>                  6276 ns         3899 ns       344615
ranges_search<std::uint16_t>                 6358 ns         3625 ns       331852
ranges_search<std::uint32_t>                 5652 ns         3692 ns       431622
ranges_search<std::uint64_t>                 7510 ns         4269 ns       373333
search_default_searcher<std::uint8_t>        1720 ns          921 ns      1120000
search_default_searcher<std::uint16_t>       2497 ns         1438 ns      1000000
search_default_searcher<std::uint32_t>       2224 ns         1001 ns      1280000
search_default_searcher<std::uint64_t>       2762 ns         1297 ns      1000000
```

After:
```
---------------------------------------------------------------------------------
Benchmark                                       Time             CPU   Iterations
---------------------------------------------------------------------------------
c_strstr                                      183 ns          102 ns     10000000
ranges_search<std::uint8_t>                   678 ns          355 ns      4266667
ranges_search<std::uint16_t>                 1285 ns          698 ns      1723077
ranges_search<std::uint32_t>                 2317 ns         1111 ns      1280000
ranges_search<std::uint64_t>                 4736 ns         2537 ns       597333
search_default_searcher<std::uint8_t>         669 ns          353 ns      4072727
search_default_searcher<std::uint16_t>       1293 ns          582 ns      1906383
search_default_searcher<std::uint32_t>       2261 ns         1400 ns       814545
search_default_searcher<std::uint64_t>       4756 ns         2511 ns       497778
```
</details>

`strstr` is given for a reference in the benchmark, it is not affected by the optimization.

It may be impossible to reach `strstr` performance, as it uses `pcmpistri` (and reading beyond the last element, as `pcmpistri` is not very useful otherwise). We can try `pcmpestri` for 8-bit and 16-bit cases, but still it may be not as efficient, as `strstr`. I'd prefer to try this additional optimization in a next PR though.

### CODE REVIEW

**Comment by AlexGuteniev** [comment]
The difference in "before" results between `ranges::search` and `search(..., default_searcher)` is due to different implementation.  `search(..., default_searcher)` doesn't try to use `memcmp` on every iteration. It is direct comparison. Apparently, this is faster.

It is curious that `search(..., default_searcher)` is faster for 64-bit type before vectorization.

I would want someone else to confirm the results, and maintainers decision what to do with this.

**Comment by AlexGuteniev** [comment]
A possible way to handle it is to remove 32 and 64 bit optimization/vectorization attempts at all, so that `ranges::search` case (along with the usual `std::search` would be the same as `search(..., default_searcher)`

**Comment by AlexGuteniev** [comment]
And if we are to keep vectorization only for 8-bit and 16-bit elements, we may drop the current implementation and not review/commit it in the first place, if SSE4.2 `pcmpestri` smells like it would be faster.

**Review by StephanTLavavej — CHANGES_REQUESTED** [review]
Partial review - looking good so far!

**Comment by StephanTLavavej** [comment]
I pushed changes to address the issues that I found, but I still need to think about whether we should be vectorizing this at all. I'm leaning towards ripping out the existing `memcmp`. Stay tuned...

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Ok, after looking at the benchmarks, I've taken the radical step of reverting both the vectorization changes *and* the existing `memcmp` "optimizations" that were massively pessimizing your reasonable benchmark example. My measurements:

Benchmark                                | `main`  | Vector  | Plain
-----------------------------------------|---------|---------|--------
`c_strstr`                               |  144 ns |  151 ns |  145 ns
`classic_search<std::uint8_t>`           | 8935 ns | 1726 ns | 1754 ns
`classic_search<std::uint16_t>`          | 9732 ns | 3017 ns | 1739 ns
`classic_search<std::uint32_t>`          | 9029 ns | 4829 ns | 1912 ns
`classic_search<std::uint64_t>`          | 8970 ns | 8471 ns | 2527 ns
`ranges_search<std::uint8_t>`            | 8916 ns | 1723 ns | 1784 ns
`ranges_search<std::uint16_t>`           | 8932 ns | 3012 ns | 1785 ns
`ranges_search<std::uint32_t>`           | 8303 ns | 4840 ns | 2460 ns
`ranges_search<std::uint64_t>`           | 9061 ns | 8577 ns | 1860 ns
`search_default_searcher<std::uint8_t>`  | 1858 ns | 1720 ns | 1883 ns
`search_default_searcher<std::uint16_t>` | 2525 ns | 3016 ns | 1861 ns
`search_default_searcher<std::uint32_t>` | 1863 ns | 4812 ns | 1869 ns
`search_default_searcher<std::uint64_t>` | 1873 ns | 8440 ns | 2592 ns

This compares `main` (with only the benchmark added), this vectorization PR before my revert, and finally "Plain" which lacks both vectorization and `memcmp`.

There's some noise here (e.g. `search_default_searcher` is unchanged between `main` and Plain, but there were random 2500 ns spikes), but the pattern is quite clear: `memcmp` is almost a 5x penalty for all element sizes, vectorization helps smaller elements, but plain code results in great performance across the board.

Note that dropping the `memcmp` paths from `_Equal_rev_pred_unchecked` and `_Equal_rev_pred` has very limited impact. `_Equal_rev_pred_unchecked` is called by classic/parallel `search`/`find_end`, and `_Equal_rev_pred` is called by ranges `search`/`find_end`. (This makes sense, since `find_end` is the "opposite" of `search`.)

The `equal` etc. algorithms aren't affected by this. We should probably evaluate their use of `memcmp`, but I expect the behavior to be quite different (and I hope that `memcmp` is beneficial). It's `search`/`find_end` that are unusual because they want to *repeatedly* compare a needle, which has very different performance characteristics.

In addition to keeping the benchmark from this vectorization attempt, I've also kept the correctness test (even though `search` is no longer vectorized), since it's quick to run, and we might figure out how to vectorize this beneficially in the future.

**Comment by AlexGuteniev** [comment]
> The `equal` etc. algorithms aren't affected by this. We should probably evaluate their use of `memcmp`, but I expect the behavior to be quite different (and I hope that `memcmp` is beneficial)

Agreed. `mismatch` / `lexicographical_compare` did benefit from similar optimization.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for investigating and improving the performance here even if the final result was very different from the initial vision! :crystal_ball: :magic_wand: :rocket:

**Pull request merged**
