### PR TITLE
Update _MSVC_STL_UPDATE to January 2023 #3317

### LINKED ISSUE #3317: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to January 2023
Explanation on our wiki: [Macro _MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code: https://github.com/microsoft/STL/blob/8ddf4da23939b5c65587ed05f783ff39b8801e0f/stl/inc/yvals_core.h#L799

Previous issue: #3251

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by maximd-g**
Resolves #3317

### CODE REVIEW

**Review by CaseyCarter — APPROVED** [review]
LGTM - thanks!

**Review by StephanTLavavej — APPROVED** [review]

**Review by fsb4000 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! :calendar: :smile_cat: :tada:

This will ship in VS 2022 17.6 Preview 2, and is likely to be the final value for VS 2022 17.6.

**Comment by maximd-g** [comment]
Thank you!

**Pull request merged**
