### PR TITLE
Add a table of contents to README.md

### PR DESCRIPTION
**Pull request by alexriegler**
Adds a table of contents (TOC) to README.md.

The purpose of this change is to make the README easier to digest and navigate through.

The TOC does not include the top-most header.

I placed the TOC in a details section so that it is collapsible. I did this to keep the profile of the README similar to before.

Optionally, the TOC could be its own section that's not collapsible. However, I feel that this adds too much noise to the top of the README.

One point of consideration is, what is the ideal depth for the TOC? Right now, there is no depth limit. I think it's fine without a depth limit (includes all headers, except first).

Additionally, if a TOC were added, future modifications to sections in the README would need to also update the TOC. It doesn't seem like the sections of the README are changed frequently so this should be fine.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Thanks for looking into improving the README!

Note that GitHub added an [auto-generated ToC](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/) one year ago. Here's what it looks like:

readme1
readme2

Because it's outside the document itself, it has the advantage of remaining visible even after scrolling down:

readme3

It shares the ability to depict nesting (of `# Headings`, `## Subheadings`, etc.):

readme4

And because it's auto-generated, it can't get out of sync during maintenance.

The disadvantage of the auto-generated ToC is that it isn't customizable.

I'll label this as `decision needed` - there's a weekly maintainer meeting on Wednesdays, so we can decide whether a manual ToC is worth the (minor) visual complexity of the collapsed line and the (also minor) maintenance cost.

**Comment by alexriegler** [comment]
Oh wow, that's a very neat feature of GitHub I never knew about! Thanks for letting me know! I probably never noticed it since it's so subtle but I guess that's a GitHub issue. I'll make sure to tell all of my friends (that use GitHub) about that little ToC button!

[After contemplating a bit about why I never noticed that little button...]
I think I never noticed the button because some other popular repositories that I've seen (for example, [vcpkg](https://github.com/Microsoft/vcpkg) and [Abseil](https://github.com/abseil/abseil-cpp)) have explicit ToCs written out in their READMEs so it's a habit of mine to look for a ToC written out in the README and if it's not there, I assume they just don't have one (prior to learning about the ToC button). Many of those popular READMEs were probably written before the auto-generated ToC feature was added so they probably just haven't switched over yet or maybe they like the inline ToC better.

So maybe it'd be useful to have the inline ToC in the README just for the folks like me who are used to ToCs written out in the README and aren't aware of the tiny ToC button in the corner of the README.

But I think it might be likely that I'm in the minority here and someone should let those other projects know that they no longer need to maintain a handwritten ToC in their READMEs since GitHub automatically generates one.

I'm leaning towards keeping the README as is (close this PR without merging). The reason being that less things to maintain is a good thing and the auto-generated ToC is good enough.

Lastly, I have a question related to documentation PRs , is there a way to submit a PR and not trigger the builds and tests? This would only be useful for PRs that don't touch any files involved in the build process (for example, just the README) but if it were possible, it would prevent unnecessary resource usage and could allow for faster feedback (you wouldn't need to wait for the builds and tests).

**Comment by StephanTLavavej** [comment]
:smile_cat:

> I'm leaning towards keeping the README as is (close this PR without merging). The reason being that less things to maintain is a good thing and the auto-generated ToC is good enough.

Ok, thanks. I'll check with the other maintainers before closing, just to be sure.

> Lastly, I have a question related to documentation PRs , is there a way to submit a PR and not trigger the builds and tests?

It appears to be possible to configure Azure Pipelines to `exclude` certain `paths` with wildcards: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&preserve-view=true&tabs=yaml#wildcards

However, we would want "Code Format Validation" to run even for README changes - this checks for overly long lines, tabs, and non-ASCII characters (like smart quotes and long dashes):
https://github.com/microsoft/STL/blob/bf3ac95af7438f818eac1754c9f16cfdb416cd23/azure-pipelines.yml#L16
https://github.com/microsoft/STL/blob/bf3ac95af7438f818eac1754c9f16cfdb416cd23/tools/validate/validate.cpp#L167-L174

I don't know if `azure-pipelines.yml` can be configured to always run Code Format Validation (which is very fast/cheap - just one VM running for less than a minute), but skip the "build and test" stages for documentation-only changes. (We did figure out how to express dependencies - so if Code Format Validation fails, we don't run the expensive builds/tests at all, and we also run just the x64 builds/tests first, and only if they pass do we run the remaining architectures x86/ARM/ARM64 which can reduce the cost/time for failed runs to just 25%).

If you can find out how to express this in Azure Pipelines, we would be interested!

**Comment by StephanTLavavej** [comment]
Closing as previously discussed - thanks again! :smile_cat:

**Pull request closed without merging**
