### PR TITLE
Run CTest tests serially to avoid oversubscribing cores

### PR DESCRIPTION
**Pull request by horenmar**
The lit tests are already internally parallelized, so using CTest to run them in parallel ends up with the CPU cores hopelessly oversubscribed.

### CODE REVIEW

**Review by fsb4000 — APPROVED** [review]
I've checked that the CI time doesn't change after the update, and I also consulted the CMake documentation to ensure there were no misspellings:
https://cmake.org/cmake/help/latest/command/set_tests_properties.html
https://cmake.org/cmake/help/latest/prop_test/RUN_SERIAL.html

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! I never run `ctest` (instead I always invoke `stl-lit.py` directly), so I didn't realize it was trying to run `stl` and `stlasan` simultaneously with separate Python invocations. Great catch :heart_eyes_cat:

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks again! :tada: :smile_cat: :rocket:

**Pull request merged**
