### PR TITLE
LWG-3769 `basic_const_iterator::operator==` causes infinite constraint recursion

### LINKED ISSUE #3436: LWG-3878 `import std;` should guarantee initialization of standard iostreams objects
LWG-3878 `import std;` should guarantee initialization of standard iostreams objects

Need to investigate whether our iostreams machinery achieves this automatically, or if we need to do something special for Standard Library Modules. It sure seems like I can use `cout` normally.

### LINKED ISSUE #3458: LWG-3769 `basic_const_iterator::operator==` causes infinite constraint recursion
LWG-3769 `basic_const_iterator::operator==` causes infinite constraint recursion

We implemented a previous proposed resolution, but not the final resolution of this issue approved by WG21.

### PR DESCRIPTION
**Pull request by CaseyCarter**
We implemented an earlier version of the resolution, this is the final version approved by WG21.

Fixes #3458

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
This has the same edits at the end of `<xutility>` as #3461 where the comments `// Per LWG-3664` are being removed. Unintentional mixing of PRs?

**Comment by CaseyCarter** [comment]
> This has the same edits at the end of `<xutility>` as #3461 where the comments `// Per LWG-3664` are being removed. Unintentional mixing of PRs?

Yes, I made all of these changes together, then failed to split them into two PRs. Fixed.

**Review by strega-nil-ms — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this infinitely recurring issue! :infinity: :joy_cat: :hammer_and_wrench:

**Pull request merged**
