### PR TITLE
updated working draft revision to N4950

### LINKED ISSUE #3695: `README.md`: Update working draft revision to N4950
[N4950](https://wg21.link/n4950) is the latest C++ working draft, it replaces [N4944](https://wg21.link/n4944).

Code:
https://github.com/microsoft/STL/blob/5404ba9c25f26f25a0ac50e6c4defce7833a8da6/README.md#L61 https://github.com/microsoft/STL/blob/5404ba9c25f26f25a0ac50e6c4defce7833a8da6/README.md#L535

Previous issue: #3590.

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by Tonystark121**
Updated working draft revision from N4944 to N4950.
Fixes N4944/N4950 on line 535.
Fixes #3695

### CODE REVIEW

**Review by JMazurkiewicz — CHANGES_REQUESTED** [review]
* Your PR's description should be linked to #3307 issue with [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword),
* You should also update WD revision on line 535.

**Review by StephanTLavavej — APPROVED** [review]

**Review by fsb4000 — APPROVED** [review]

**Comment by Tonystark121** [comment]
Thanks for bringing these up to the latest draft! 🎉

**Review by barcharcraz — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by Tonystark121** [comment]
@StephanTLavavej  no further changes is pushed

**Comment by CaseyCarter** [comment]
Thanks for making the STL more drafty 🌬️🎐🌪️, and **🎉🎉Congratulations on your first STL contribution! 🎉🎉**

**Comment by Tonystark121** [comment]
Thank you 🎉🎉🎉

**Pull request merged**
