### PR TITLE
_MSVC_STL_UPDATE changed of current month

### PR DESCRIPTION
**Pull request by 2002Bishwajeet**
Fixed issue #1799

### CODE REVIEW

**Review by mnatsuhara — APPROVED** [review]
Looks great! 👍

**Review by CaseyCarter — APPROVED** [review]
All good. Congratulations on your first STL PR!

**Comment by 2002Bishwajeet** [comment]
Thank You so much for approving them😊. I would like to contribute more, can you guide me further on what to do next??

**Review by fsb4000 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! :tada: :smiley_cat:

As @mnatsuhara mentioned on Discord, the maintainer team is busy with finishing C++20 so our ability to provide guidance is limited at the moment. After briefly looking over our issues list, I think that further PRs to improve #206 could be suitable. Instead of trying to apply `_NODISCARD` to the entire STL (which would be a ton of work), you can pick just one header (or a small handful) and look for opportunities to apply `_NODISCARD` following our criteria. #1474 is an excellent example of such a PR.

**Pull request merged**
