### PR TITLE
Update env.lsts for improved vcruntime detection of Clang mode

### LINKED ISSUE #2232: `<ranges>`: namespace `views` not available with clang-cl
**Describe the bug**
`<ranges>`: namespace `views` not available with clang-cl

**Command-line test case**
```c++
#include <iostream>
#include <ranges>
#include <vector>

int main()
{
    std::vector<int> ints{ 0, 1, 2, 3, 4, 5 };

    auto x = ints | std::ranges::views::transform([](auto i) { return i * i; });
}
```

```
d:\temp2>cl /std:c++latest test.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.30.30528 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

/std:c++latest is provided as a preview of language features from the latest C++
working draft, and we're eager to hear about bugs and suggestions for improvements.
However, note that these features are provided as-is without support, and subject
to changes or removal as the working draft evolves. See
https://go.microsoft.com/fwlink/?linkid=2045807 for details.

test.cpp
Microsoft (R) Incremental Linker Version 14.30.30528.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:test.exe
test.obj

d:\temp2>clang-cl /std:c++latest test.cpp
test.cpp(9,34): error: no member named 'views' in namespace 'std::ranges'
    auto x = ints | std::ranges::views::transform([](auto i) { return i * i; });
                    ~~~~~~~~~~~~~^
1 error generated.
```

**Expected behavior**
clang-cl should compile it

**STL version**
```
Version 17.0.0 Preview 4.1
```

**Additional context**
This is also tracked as DevCom-1544711

### PR DESCRIPTION
**Pull request by CaseyCarter**
VCRuntime now recognizes Clang's `/std:c++20` and `/std:c++latest` modes without the "`/std:c++latest` with or without `/D_HAS_CXX23`" hack.

Fixes #2232

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Relabeling - the original issue was reasonably reported as a bug, but this PR is a test-only cleanup, unless I am totally confused.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by CaseyCarter** [comment]
> Relabeling - the original issue was reasonably reported as a bug, but this PR is a test-only cleanup, unless I am totally confused.

That's fine. I was mindlessly following the "resolves issue tagged [bug], tag PR with [bug]" rule of thumb.

**Review by barcharcraz — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for eradicating this hack! Can't believe how many times I got confused by trying to run Clang with `/std:c++latest` alone. :joy_cat: :rocket: :tada:

**Pull request merged**
