### PR TITLE
Update _MSVC_STL_UPDATE to September 2023

### LINKED ISSUE #4001: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to September 2023
Explanation on our wiki: [Macro _MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code: https://github.com/microsoft/STL/blob/782dcd536a57fd5c6a215d1b9a3014ba4c25282f/stl/inc/yvals_core.h#L876

Previous issue: #3917

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by kissholic**
Fixes #4001

### CODE REVIEW

**Comment by fsb4000** [comment]
Edit your first post to `Fixes #4001`

**Review by sam20908 — APPROVED** [review]
BTW, the title of the PR is probably meant to say "September" :)

**Review by CaseyCarter — APPROVED** [review]
The change is good. I've changed "August" to "September" in the title, and added "Fixes #4001" to the description so the issue is linked to the PR (and will be automagically closed when the PR merges). Thanks!

**Review by StephanTLavavej — APPROVED** [review]

**Review by fsb4000 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro and congratulations on your first microsoft/STL commit! :tada: :smile_cat: :rocket:

**Pull request merged**
