### PR TITLE
Fix 2 VS 16.8p3 blocked issues

### LINKED ISSUE #1152: Change libcxx SKIPPED to FAIL when MSVC ships P0960
MSVC has implemented (but not yet shipped) support for P0960R3 "Allow initializing aggregates from a parenthesized list of values". The libcxx test `std/utilities/tuple/tuple.tuple/tuple.creation/tuple_cat.pass.cpp` is broken by this C++20 feature, so we recently SKIPPED it in `tests/libcxx/expected_results.txt` and `tests/libcxx/skipped_tests.txt`. Once VS 2019 v 16.8p3 ships - which is expected to include the P0960 support - we should change the `SKIPPED` in `tests/libcxx/expected_results.txt` to an expected failure for MSVC only which IIRC corresponds to:
```diff
 # *** CLANG FEATURES NOT YET IMPLEMENTED ***
 # P0960R3 "Allow initializing aggregates from a parenthesized list of values"
-std/utilities/tuple/tuple.tuple/tuple.creation/tuple_cat.pass.cpp SKIPPED # TRANSITION, VS 2019 16.8 p3
+std/utilities/tuple/tuple.tuple/tuple.creation/tuple_cat.pass.cpp:0 FAIL

```

(A better fix would be to fix this test upstream and remove the skips, but we're currently blocked from updating LLVM due to LIT changes; see #1090.)

### PR DESCRIPTION
**Pull request by SuperWig**
Fixes #1152 and #1199

### CODE REVIEW

**Comment by SuperWig** [comment]
Interesting, it only auto linked one of the issues. 😕

**Review by CaseyCarter — APPROVED** [review]

**Comment by cbezault** [comment]
@SuperWig https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/azure-repos-git?view=azure-devops&tabs=yaml#skipping-ci-for-individual-commits

**Review by cbezault — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
> Interesting, it only auto linked one of the issues, I guess it doesn't understand "and".

That's correct - the Words Of Power must be repeated. See: https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
After #1290 merges, we'll push a merge to this PR, and assuming the tests are green, we'll move to Ready To Merge. Thanks!

**Comment by cbezault** [comment]
Woops, I thought it had gotten merged.

**Comment by CaseyCarter** [comment]
> Woops, I thought it had gotten merged.

I think you beat me by ten minutes or so.

**Comment by StephanTLavavej** [comment]
Thanks for following up on these issues - removing workarounds helps our compilers stay conformant! :smile_cat:

**Pull request merged**
