### PR TITLE
Remove <vector> - who needs it, anyway?

### PR DESCRIPTION
**Pull request by CaseyCarter**

### CODE REVIEW

**Comment by CaseyCarter** [comment]
This is terrible idea, no way!

**Comment by BillyONeal** [comment]
I'm very confused

**Comment by CaseyCarter** [comment]
> I'm very confused

I needed a PR to test the Project PR automation.

**Comment by StephanTLavavej** [comment]
And we learned that new PRs aren't automatically added to the New column of the Code Reviews Project. Instead, when a PR is added (manually) to the Code Reviews Project, the automation will automatically move it to the New column - helpful, but not quite what we originally hoped for.

**Comment by miscco** [comment]
And I first thought @ThePhD went to town with the new project ^^

**Pull request closed without merging**
