### PR TITLE
Cache the "installed" vcpkg directory only.

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by BillyONeal** [comment]
Verified this gets our build time down to ~1:30 from ~2:20 with a cache hit on the 16 core VMs.

**Comment by lukka** [comment]
The change looks fine to me, because caching installed folder is all you need to run a build, it is not allowing you to run vcpkg again, which is a sanity check that ensures you have the correct set of dependencies restored by the cache. `vcpkg` does not have currently  a 'desired state configuration' command, and what the `run-vcpkg` task currently does (i.e. removing outdated and then try to install what could be potentially already there) is the best solution to resemble that.

So my 2 cents, I would rather suggest to:
-always run `run-vcpkg`, that is a no-op (<1sec) and that ensures in the build log that you have installed the packages you believe are installed in the restored cache;
-cache (with the `cache` task) all files of vpckg, the task will take care of removing not necessary files (i.e. downloads, packages and buildtrees directories); also by default the `--clean-after-build` is always passed to run-vcpkg;
-the key used for caching must take into account both version of vcpkg, and the set of packages that are installed, along with the triplet; in this case the latter are missing;

I think i could just create another PR that applies the above that would show that:
-the cache size wont be a problem compared to just caching installed cause cleaning is in action already; 
-the time for build would increase of <=1sec;
-the added value is that you know for any build what has been restored (this is ensured by running vcpkg all the time);

**Comment by BillyONeal** [comment]
@lukka If we change the set of ports installed we'll bump the datestamp.

> I would rather suggest to: -always run run-vcpkg

That's sadly what we're currently doing and it's resulting in 30% longer build times than we could otherwise use. However, the run-cmake task needs vcpkg available to do `vcpkg.exe env`, so avoiding it there isn't possible.

>cache (with the cache task) all files of vpckg, the task will take care of removing not necessary files (i.e. downloads, packages and buildtrees directories); also by default the --clean-after-build is always passed to run-vcpkg

That's what we were doing before this PR and it results in caching more than twice as much stuff (~230MB -> ~740MB). We're observing bottlenecks / throttling of our builds on the part of whatever service is hosting this caching.

**Comment by lukka** [comment]
> @lukka If we change the set of ports installed we'll bump the datestamp.

I still prefer the smoother solution where you use your own "package.json" file instead (a vcpkg response file in your case), it would be less error prone.

> > I would rather suggest to: -always run run-vcpkg
> 
> That's sadly what we're currently doing and it's resulting in 30% longer build times than we could otherwise use **(since it forces us to build vcpkg.exe)**. However, the run-cmake task needs vcpkg available to do `vcpkg.exe env`, so avoiding it there isn't possible.
> 

I changed the check of  `run-vcpkg` and now it is not trying to rebuild vcpkg if it is not needed. Of course, you need to cache `vcpkg.exe` as well, because the task really wants to run it :)

> > cache (with the cache task) all files of vpckg, the task will take care of removing not necessary files (i.e. downloads, packages and buildtrees directories); also by default the --clean-after-build is always passed to run-vcpkg
> 
> That's what we were doing before this PR and it results in caching more than twice as much stuff (~230MB -> ~740MB). We're observing bottlenecks / throttling of our builds on the part of whatever service is hosting this caching.

That is fixed as well, the cached size should be what you expect now. 

To verify all of the above, I am going to create a PR with a new Cache's key that would show that the cache size and the build time should meet your expectation.

**Comment by BillyONeal** [comment]
>I changed the check of run-vcpkg and now it is not trying to rebuild vcpkg if it is not needed

Maybe we have to poke something to see that change?

>To verify all of the above, I am going to create a PR with a new Cache's key that would show that the cache size and the build time should meet your expectation.

OK, I'll merge this as is now and look forward to your shinier solution :)

**Comment by lukka** [comment]
> > I changed the check of run-vcpkg and now it is not trying to rebuild vcpkg if it is not needed
> 
> Maybe we have to poke something to see that change?

Yes, there is a file containing the commitid that is generated after vcpkg.exe been successfully built. If this file is not cached, the run-vcpkg task will keep re-building it. I can read on the build log 

[ `"There is no file containing last built commit id of vcpkg, forcing a rebuild."`](https://dev.azure.com/vclibs/STL/_build/results?buildId=1658&view=logs&j=89e509dc-b698-550e-ac31-eaa041004158&t=ab374b13-da5a-5e27-f919-adc0647a4fac&l=16)
 that confirms it.

> 
> > To verify all of the above, I am going to create a PR with a new Cache's key that would show that the cache size and the build time should meet your expectation.
> 
> OK, I'll merge this as is now and look forward to your shinier solution :)

👍

**Pull request merged**
