### PR TITLE
Properly constrain `_Movable_box`'s copy constructors

### PR DESCRIPTION
**Pull request by CaseyCarter**
We failed to add constraints when implementing the _`copyable-box`_ to _`movable-box`_ relaxation.

Drive-by: Rename `_Not_same_as` to `_Different_from` for consistency with the name change in the working draft.

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Comment by JMazurkiewicz** [comment]
Note: code introduced by #3043 still uses `_Not_same_as`.

**Comment by StephanTLavavej** [comment]
@JMazurkiewicz Thank you for noticing the stealth build break! :heart_eyes_cat: :heart_eyes_cat: :heart_eyes_cat:

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug that had such surprisingly complicated consequences, and for aligning the exposition-only concept's naming with the Working Draft! :package: :package: :package:

**Comment by CaseyCarter** [comment]
> Thanks for fixing this bug that had such surprisingly complicated consequences, and for aligning the exposition-only concept's naming with the Working Draft! 📦 📦 📦

Dare I mention that the concept's name is no longer... _different-from_ the working draft? 😎

**Comment by CaseyCarter** [comment]
(I'm so tempted to changelog this insignificant internal change as "Upon noticing that `_Not_same_as` was not the same as the name of the exposition-only concept in the working draft, renamed to `_Different_from` so it would no longer be _different-from_ the working draft's name.")

**Pull request merged**
