### PR TITLE
Implement P2499R0: `string_view` Range Constructor Should Be `explicit`

### LINKED ISSUE #2935: P2499R0 `string_view` Range Constructor Should Be `explicit`
[P2499R0](https://wg21.link/P2499R0) `string_view` Range Constructor Should Be `explicit`

This paper doesn't mention any feature-test macros, presumably intentionally.

### PR DESCRIPTION
**Pull request by sam20908**
Fixes #2935

### CODE REVIEW

**Review by CaseyCarter — CHANGES_REQUESTED** [review]
We need to add an entry for `P2499R0 string_view Range Constructor Should Be explicit` in the "[features] controlled by `_HAS_CXX23`" section of `<yvals_core.h>`" (Yes, this isn't much of a feature, but that's the process.) somewhere around line 317. (They're ordered by proposal number.)

**Comment by StephanTLavavej** [comment]
It appears that one more libcxx test needs to be skipped:

## `cl` error
```
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(102): error C2440: 'initializing': cannot convert from 'const test::DeletedConversionOperator' to 'std::basic_string_view<char,std::char_traits<char>>'
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(102): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(108): error C2280: 'test::DeletedConstConversionOperator::operator std::basic_string_view<char,std::char_traits<char>>(void) const': attempting to reference a deleted function
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(91): note: see declaration of 'test::DeletedConstConversionOperator::operator std::basic_string_view<char,std::char_traits<char>>'
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(91): note: 'test::DeletedConstConversionOperator::operator std::basic_string_view<char,std::char_traits<char>>(void) const': function was explicitly deleted
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(102): error C2440: 'initializing': cannot convert from 'const test::DeletedConversionOperator' to 'std::basic_string_view<char,std::char_traits<char>>'
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(102): note: No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(192): note: while evaluating constexpr function 'test'
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(192): error C2131: expression did not evaluate to a constant
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(102): note: a non-constant (sub-)expression was encountered
```

## `clang-cl` error
```
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(102,34): error: no viable conversion from 'const DeletedConversionOperator' to 'std::basic_string_view<char>'
    std::basic_string_view<char> csv = d;
                                 ^     ~
D:\build\out\inc\xstring(1223,15): note: candidate constructor not viable: no known conversion from 'const DeletedConversionOperator' to 'const std::basic_string_view<char> &' for 1st argument
    constexpr basic_string_view(const basic_string_view&) noexcept            = default;
              ^
D:\build\out\inc\xstring(1226,30): note: candidate constructor not viable: no known conversion from 'const DeletedConversionOperator' to 'const std::basic_string_view<char>::const_pointer' (aka 'const char *const') for 1st argument
    /* implicit */ constexpr basic_string_view(_In_z_ const const_pointer _Ntcts) noexcept // strengthened
                             ^
D:\build\out\inc\xstring(1230,5): note: candidate constructor not viable: no known conversion from 'const DeletedConversionOperator' to 'std::nullptr_t' for 1st argument
    basic_string_view(nullptr_t) = delete;
    ^
D:\build\out\inc\xstring(1263,24): note: explicit constructor is not a candidate
    constexpr explicit basic_string_view(_Range&& _Rng) noexcept(
                       ^
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(84,5): note: candidate function not viable: 'this' argument has type 'const DeletedConversionOperator', but method is not marked const
    operator std::basic_string_view<char>() = delete;
    ^
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(108,34): error: conversion function from 'DeletedConstConversionOperator' to 'std::basic_string_view<char>' invokes a deleted function
    std::basic_string_view<char> sv = dc;
                                 ^    ~~
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(91,5): note: 'operator basic_string_view' has been explicitly marked deleted here
    operator std::basic_string_view<char>() const = delete;
    ^
C:\a\1\s\llvm-project\libcxx\test\std\strings\string.view\string.view.cons\from_range.pass.cpp(192,17): error: static_assert expression is not an integral constant expression
  static_assert(test());
                ^~~~~~
3 errors generated.
```

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Perfect, thanks!

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for implementing this feature, following the original one you implemented! :heart_eyes_cat: :white_check_mark: :rocket:

**Pull request merged**
