### PR TITLE
system_error: Map errc::broken_pipe to ERROR_BROKEN_PIPE.

### PR DESCRIPTION
**Pull request by DaanDeMeyer**
# Description

I noticed `std::error_code(ERROR_BROKEN_PIPE, std::system_category()) == std::errc::broken_pipe` didn't work so I checked the source and found there isn't a mapping for it. This PR adds the missing mapping.

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [x] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

**Comment by BillyONeal** [comment]
I believe this was the first bug I tried to fix on the VC++ team but there were some ABI concerns (namely, because it changes the behavior of the DLL so programs that get an updated redist might have different behavior). @stwish-msft I vaguely recall the UCRT making a similar change though recently and it worked out OK? (I'd tag Anju but I don't know if she has a GH account...)

**Comment by DaanDeMeyer** [comment]
A workaround for anyone else that comes upon this PR should this not be able to be fixed:

https://github.com/DaanDeMeyer/reproc/commit/dd49191cdc7b6cc76f4d86204cedc71d2448296f

**Comment by BillyONeal** [comment]
I replicated our old-as-the-hills internal bug about this as #413

**Comment by BillyONeal** [comment]
Thanks for your contribution!

**Pull request merged**
