### PR TITLE
Replace __pragma with _Pragma

### LINKED ISSUE #659: <yvals_core.h>: Use Standard _Pragma
In `<yvals_core.h>`, the STL's central internal header, we define internal helper macros for temporarily suppressing `[[deprecated]]` warnings:

https://github.com/microsoft/STL/blob/811c8c181626382ee26ea85e6963843cb17ce53e/stl/inc/yvals_core.h#L448-L468

For Clang, this uses Standard `_Pragma` to emit a `#pragma` directive within a macro. For MSVC, this uses non-Standard `__pragma`.

Our general rule is to avoid non-Standard extensions unless they're necessary. As of VS 2019 16.6 Preview 2, which the STL now requires, MSVC supports Standard `_Pragma`, so we should use it here. (We still need `#ifdef __clang__` logic because Clang and MSVC need different syntax to suppress the `[[deprecated]]` warning.)

Note: Standard `_Pragma` takes a string while non-Standard `__pragma` doesn't, as the existing code demonstrates.

### PR DESCRIPTION
**Pull request by CdTCzech**
This change was already merged as #662, but later reverted in #675.
Resolves #659

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Microsoft-internal VSO-1091758 was resolved as fixed on 2020-04-23 so it should definitely be present in VS 2019 16.8 Preview 3, yet the tests are failing. Perhaps the fix was incomplete, or didn't apply to our specific scenario; we'll need to reduce and report it on Developer Community.

**Comment by sylveon** [comment]
How does this affects VSCode? Last I tried _Pragma there it wasn't supported and cascaded into errors everywhere in my project.

**Comment by StephanTLavavej** [comment]
That's also a good question - IntelliSense is powered by the EDG front-end (which we have coverage for via the `/BE` compiler option). That's used for both VS and the VSCode C/C++ Extension.

I looked at the errors again and they appear to be MSVC's C1XX front-end (emitting normal codegen, no `/BE`) but there may be a separate issue with EDG.

**Comment by StephanTLavavej** [comment]
I've marked this as `help wanted` - the action needed here is to reduce the compiler errors here into a test case that can be reported on [Developer Community](https://developercommunity.visualstudio.com/spaces/62/index.html). This is a great opportunity to learn the mysterious art of distilling compiler errors, and to help the STL maintainers who are all busy with C++20 feature work at the moment.

**Comment by StephanTLavavej** [comment]
@fsb4000 reduced the compiler bug and filed DevCom-1224632. Marking this as `blocked` until the bug is fixed.

**Comment by StephanTLavavej** [comment]
@eldakesh-ms fixed the blocking bug with MSVC-PR-307217 in VS 2019 16.10 Preview 2. :tada:

**Comment by fsb4000** [comment]
16.10 Preview 2 is released.

**Comment by StephanTLavavej** [comment]
Yep! We just need to merge #1884 and then this should be unblocked.

**Comment by StephanTLavavej** [comment]
Argh - it appears that EDG (activated by the `/BE` compiler option) has a compiler bug affecting `_Pragma`, which we'll need to report.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Internally reported VSO-1329304 "EDG doesn't understand Standard _Pragma".

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for this long-awaited code cleanup! :date: :tada: :joy_cat: The EDG IntelliSense maintainers have enabled support for `_Pragma` although we'll need to wait for that to ship in VS before attempting to use it.

**Pull request merged**
