### PR TITLE
`<random>`: Implement LWG-3519

### LINKED ISSUE #2179: LWG-3519 Incomplete synopses for `<random>` classes
LWG-3519 Incomplete synopses for `<random>` classes

Discussion from the meta-issue #1965:
 
* @frederick-vs-ja
  > - Only implemented for `linear_congruential_engine` and non-standard `linear_congruential` (subject to removal in vNext).
  > - Note that `operator!=`s are no longer provided since C++20.
  > - Although not required by the current working draft, IMO we should...
  >   - make `operator!=`s hidden friends too,
  >   - consistently make `operator==` and `operator!=` for `param_type`s hidden friends, and remove `operator!=`s since C++20.
* @MattStephanson
  > Regarding LWG-3519, I have a branch that does most of this, but I was waiting to see if maintainers would have any comments about the partial work in #2088 on `subtract_with_carry_engine`, particularly whether this should be applied to the `tr1` classes. Also, does it need testing? I suppose that would take the form of a class that's convertible to one of the `std` types, which should now not be comparable to the `std` type. @StephanTLavavej, I see you self-assigned this 3 weeks ago, is it possible it slipped through the cracks?
* @StephanTLavavej
  > @MattStephanson I haven't had a chance to review #2088 yet as the C++20 and C++23 PRs have taken priority - it is still on the list of things I intend to review though :smile_cat: (The rate of incoming PRs has slightly exceeded our rate of reviewing them, which has led to an increasing backlog.)
  >
  > I tend to view the `tr1` classes as implementation details, which we retain for ABI and to avoid breaking legacy code (although we have deprecated them). The argument against extending recent Standard changes to them, is that we would be extrapolating the changes and that gives us the chance to get things wrong, or destabilize legacy code. The argument for would be that it would make the header more consistent, instead of appearing half-updated. I'd probably avoid extrapolating changes to `tr1` but if you wanted to, I wouldn't object as long as they didn't appear to be too disruptive.

### PR DESCRIPTION
**Pull request by MattStephanson**
Fixes #2179.

Notes:
1. I've consolidated the handling of VSO-568006 (which I can't access but assume involves `[[nodiscard]]` and hidden friends), since it comes up much more now. I'm open to a better name, though, maybe `_NODISCARD_HIDDEN_FRIEND`.
2. Maintainers indicated that LWG issues were generally higher priority than bugfixes, so I applied this to `subtract_with_carry_engine`, even though #2088 does too. I'll work with the author of that PR on a patch to resolve the merge conflict.
3. Most of the insertion and extraction operators were just forwarding to member function `_Write` or `_Read`, so I took the liberty of inlining those.
4. `piecewise_meow_distribution` were a bit subtle because of (IMO) a design mistake. They contain two `discrete_distribution<size_t>::param_type` subobjects, one from the base class and another from their own `param_type` base classes. As far as I can tell, only the latter is used, so I've tried to make this more clear. (E.g., previously `discrete_distribution::_Meow` was a non-static member function that actually meowed its `param_type` argument. Now it's a member of `param_type` that meows the object it's called on.)

### CODE REVIEW

**Comment by CaseyCarter** [comment]
> 1. I've consolidated the handling of [VSO-568006](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/568006) (which I can't access but assume involves `[[nodiscard]]` and hidden friends), since it comes up much more now. I'm open to a better name, though, maybe `_NODISCARD_HIDDEN_FRIEND`.

For posterity: VSO-568006 is an EDG bug "Attributes are not accepted on friend definitions inside class templates"
Compiling:
```c++
template <class T>
struct S {
  [[xyz]] friend int f() { return 0; }
};
```
with EDG incorrectly diagnoses:
```
"test.cpp", line 3: error: attribute "xyz" does not apply here
      [[xyz]] friend int f() { return 0; }
        ^
```
This result is independent of the choice of attribute (`xyz` vs. `nodiscard`).

**Comment by StephanTLavavej** [comment]
Thanks! As #2088 is smaller and has been waiting for review for almost 2 months, I went ahead and reviewed it, pushed changes, and moved it to Final Review. I'd like to merge it first, and then resolve the conflict in your larger PR.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Looks great! :heart_eyes_cat: I pushed a trivial style change and a merge with `main` since it had been 2 months.

I saw the minor refactorings you applied (e.g. lifting out a repeated call to `size()` in `discrete_distribution::param_type::_Write` and adding `const`) and they're all good. Also very happy to see `operator!=` guarded for C++20. I noticed pre-existing places that could be further refactored with range-for but that shouldn't become a distraction in this PR so I've recorded a todo to clean 'em up later.

**Comment by MattStephanson** [comment]
@StephanTLavavej Thanks! While I have your attention, would you mind clarifying an ABI point? I pointed out in item (4) of my first comment that I removed the `discrete_distribution::_[Read|Write]` functions and moved the functionality into the `param_type` nested class. Could you confirm that this is safe? My reasoning was that because these function have always been `inline`, any existing object files that need the definitions already have them. Therefore, it's unnecessary for new code to provide them. Is that right?

**Comment by StephanTLavavej** [comment]
Yep, that sounds right to me!

In general, changes to header-only functions are ABI-safe unless they do things like:

* Change object state that's stored across member function calls, in a way that old code wouldn't understand
* Change the observable behavior of functions (e.g. increasing the set of values that they can return), including when making coordinated changes between 2 or more functions
  + This is typically not an issue for Standard-mandated functions, since bugfixes will just make them do what they were already supposed to be doing.

In such cases, renaming the functions (and renaming affected internal classes, in the "changed object state" scenario) restores safety, since that transforms mix-and-match scenarios from the bad case of "old code links to new, incompatible code" to the good case of "old code has `_Old` functions, new code removes those and adds `_New` functions, they coexist happily". (With a slightly less strong safety factor, signature changes, especially arity changes, produce incompatible mangled names that are good enough as long as we aren't `extern "C"` and there isn't any likelihood of them changing *back*.)

Your moved functionality is equivalent to remove-and-add so it's safe. :smile_cat:

**Review by CaseyCarter — APPROVED** [review]
I'll go ahead and apply my single suggestion.

**Comment by StephanTLavavej** [comment]
@CaseyCarter I pushed a commit to fix test failures - `and` is super ultra forbidden in this codebase. (MSVC doesn't always understand it, which conveniently aligns with my personal dislike of spelling out operators :joy_cat:)

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
`and` is super ultra forbidden in this codebase

Ouch, mea culpa. (`and` is nice since it very clearly should _not_ be used to declare an rvalue reference. `and` and `not` are both growing on me.)

**Comment by StephanTLavavej** [comment]
Thanks for implementing this major LWG issue resolution and improving our workaround for CUDA here! :heart_eyes_cat: :hammer_and_wrench: :rocket:

**Pull request merged**
