### PR TITLE
Toolset update: VS 2022 17.12 Preview 3, Python 3.13.0

### PR DESCRIPTION
**Pull request by StephanTLavavej**
# :scroll: Changelog

- Code cleanups:
  * Removed compiler bug workarounds.
- Infrastructure improvements:
  * Updated dependencies.
    + Updated build compiler to VS 2022 17.12 Preview 3 (now required).
    + Updated Python to 3.13.0 (now required).

### CODE REVIEW

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
> /azp run STL-ASan-CI

[All green](https://dev.azure.com/vclibs/STL/_build/results?buildId=17697&view=results).

**Comment by StephanTLavavej** [comment]
Looks purr to me! (We usually say CUDA instead of NVCC these days, but it's not worth resetting testing.) Thanks, this one wasn't on my radar.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Pull request merged**
