### PR TITLE
Use a bitwise and instead of shifts

### PR DESCRIPTION
**Pull request by AtariDreams**
This is faster in some instances and is clearer in intent

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Thanks for looking into this!

The optimized codegen is identical: https://godbolt.org/z/K4envEYs5

I believe that the debug codegen is not important here - these are per-algorithm-call, and we generally don't worry about slightly suboptimal instruction sequences (whereas we occasionally worry about many layers of unnecessary function calls, e.g. in `invoke()`).

So the main question is clarity, which is a judgement call. I believe that the existing pattern of shifting back and forth by N more clearly expresses the intent to clear the low N bits. Marking as "decision needed" for the other maintainers to consider.

**Comment by MikeGitb** [comment]
Just a suggestion: If you want to use this notation, I'd use binary litterals instead of decimal numbers.

**Comment by AlexGuteniev** [comment]
My opinion:
 * The clear way is `* 16 / 16`, though the debug codegen is expected to be awful (with actual division)
 * I'd wrote `& 0xF`. Hex is a compact binary.
 * There's no much point to make this clearer. Those who read SSE / AVX  will not be confused by any of the opitions

**Comment by strega-nil-ms** [comment]
I strongly agree that `& ~...` is more clear than `>> N << N`; however, I would also appreciate @AlexGuteniev's heximal literal change (or even binary literal). I'm not against making this clearer.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Ok, I've validated and pushed changes to:

* Use hex literals as suggested by @AlexGuteniev and @strega-nil-ms.
* Use `~size_t{VALUE}` to start with a constant of the desired width and avoid having to think about signed-to-unsigned conversions. (`size_t & ~31` worked because `~31` is a negative `int` that gets sign-extended when converted to `size_t`, which I found highly surprising when I realized it.)
* Also change `>> 6 << 5` and `>> 5 << 4`.
  + I believe that this is a clarity improvement, as this makes the division by 2 (followed by masking) more obvious, so I am now in favor of this change.

Codegen is unaffected: https://godbolt.org/z/h7qE3vca1

Thanks again!

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for this code cleanup! :smile_cat: :smile_cat: :smile_cat: :smile_cat: :smile_cat: :smile_cat: :smile_cat: :smile_cat:

**Pull request merged**
