### PR TITLE
Updated _MSVC_STL_UPDATE to February 2023

### LINKED ISSUE #3374: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to February 2023
Explanation on our wiki: [Macro _MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code: https://github.com/microsoft/STL/blob/f8b8ad6dea901d360d8165cc6719de47ca9d9ca2/stl/inc/yvals_core.h#L815

Previous issue: #3317

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by MikiPAUL**
Closes #3374

### CODE REVIEW

**Comment by fsb4000** [comment]
`Closes #3374`, not `Closes issue https://github.com/microsoft/STL/issues/3374`

**Review by fsb4000 — APPROVED** [review]

**Review by JMazurkiewicz — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]
Looks good. Thanks!

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! :heart_eyes_cat: :tada: :rocket:

This will ship in VS 2022 17.7 Preview 1.

**Comment by MikiPAUL** [comment]
Thank you!!

**Pull request merged**
