### PR TITLE
updated _MSVC_STL_UPDATE to January 2022

### LINKED ISSUE #2454: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to January 2022
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/303df3dae6f5ed9fe4f1c35257f663af8355584a/stl/inc/yvals_core.h#L584

Previous issue: #2371

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### PR DESCRIPTION
**Pull request by ssenthilnathan3**
Fixes #2454

### CODE REVIEW

**Review by fsb4000 — COMMENTED** [review]
Add `Fixes #2454` to your PR description.

Similar to my PR: https://github.com/microsoft/STL/pull/2443

**Review by fsb4000 — APPROVED** [review]

**Review by miscco — APPROVED** [review]
Congratulations for your first PR 🎉

**Comment by ssenthilnathan3** [comment]
> Congratulations for your first PR 🎉

Thankyou.

**Review by sam20908 — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Review by ddr533 — APPROVED** [review]
Nice work!

**Comment by ssenthilnathan3** [comment]
> Nice work!

Thnak you.

**Review by mnatsuhara — APPROVED** [review]

**Comment by CaseyCarter** [comment]
I'm going to add this to the next batch of changes to merge - please notify me if any further commits are pushed.

**Comment by CaseyCarter** [comment]
Thanks for the update and congratulations on your first STL commit! 🎉🎉🎉 😹

**Pull request merged**
