### PR TITLE
Create time_update.yml

### PR DESCRIPTION
**Pull request by steve02081504**
### A workflow to automatically update the time in the definition of yvals_core.h every month

Sections that may need to be modified:
- [ ] Add token for push
- [ ] Change the commit author information

### CODE REVIEW

**Comment by steve02081504** [comment]
@microsoft-github-policy-service agree

**Comment by StephanTLavavej** [comment]
Thanks for the PR. However, I don't think we can merge this, for a couple of reasons:

* We can't accept code that's been taken from another repo without appropriate licensing.
* Because our development happens on GitHub but the MSVC toolset is still built and shipped Microsoft-internally, we follow a process where commits are semi-manually mirrored and simultaneously merged, so that the repos are binary-identical at all times. This wouldn't work if there were any automatic GitHub commits. (In contrast, our Status Chart branch does have an automatic commit workflow, because it has no MSVC-internal counterpart.)

Thanks again for looking into how to automate this process! I think it'll be fine to continue updating manually - it actually provides a nice reason to create a "good first issue" every month and welcome contributors to GitHub by getting started with something very easy.

**Comment by steve02081504** [comment]
@StephanTLavavej Thanks for your patience in explaining this!
- First of all, although I copied and modified this file from another project, I wrote this file and I don't think this prevents open source license related issues. Thanks for the heads up though, I have now added the LICENSE file to the original project.
- Secondly, I see that you didn't close the issue but attached the tag that requires a decision, should I close the issue?

**Comment by sam20908** [comment]
I have mixed feeling about this PR: It is neat that this updates the value automatically, but that value also has a purpose, which is to allow the simplest change for a new contributor. This PR would destroy the purpose of the value, and no longer giving new contributors a chance to contribute.

**Comment by StephanTLavavej** [comment]
Apologies for the delay in responding - we talked about this at the weekly maintainer meeting and will go ahead and close this PR for the reasons that we explained. Thanks again for looking into this - we appreciate it even if we couldn't merge your change!

**Pull request closed without merging**
