### PR TITLE
enable asan for all tests

### PR DESCRIPTION
**Pull request by fsb4000**

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
This is an admirable idea, but until we find and fix the root cause of #2908, I think that actually enabling such widespread coverage would be cat-astrophic. :smirk_cat:

**Comment by fsb4000** [comment]
Yep, let the PR be blocked for now.

**Comment by StephanTLavavej** [comment]
We talked about this at the weekly maintainer meeting - @strega-nil-ms won't have time to investigate the sporadic failure #2908 any time soon, so we're going to close this PR without merging. In the future, when ASAN (hopefully) becomes reliable, we can consider making this change.

**Comment by frederick-vs-ja** [comment]
It seems that #2908 is fixed in upstream. Should we reopen this PR?

**Comment by fsb4000** [comment]
As I understand no, because Casey's PR was merged: https://github.com/microsoft/STL/pull/4052

**Pull request closed without merging**
