### PR TITLE
Update N4988 to N4993 in README.md

### LINKED ISSUE #5018: `README.md`: Update working draft revision to N4993
[N4993](https://wg21.link/n4993) is the latest C++ working draft, it replaces [N4988](https://wg21.link/n4988).

Code:

https://github.com/microsoft/STL/blob/926d458f82ae1711d4e92c0341f541a520ef6198/README.md#L61

https://github.com/microsoft/STL/blob/926d458f82ae1711d4e92c0341f541a520ef6198/README.md#L572

Previous issue: #4881.

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by 5AIPAVAN**
* Fixes #5018
Update N4988 to N4993 in README.md to resolve the issue

### CODE REVIEW

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
FYI for next time, the "-" in `Fixes -#5018` in your description breaks GitHub's magic detection. It looks for `<magic word><whitespace>#<issue-number>` and any other noise in that string causes issues (pun intended). I've corrected it.

Thanks for the PR! We merge things in batches every few days, so this will probably sit around till the middle of next week before it is merged.

**Review by frederick-vs-ja — APPROVED** [review]

**Comment by 5AIPAVAN** [comment]
> FYI for next time, the "-" in `Fixes -#5018` in your description broke GitHub's magic detection. It looks for `<magic word><whitespace>#<issue-number>` and any other noise in that string causes issues (pun intended). I've corrected it.
> 
> Thanks for the PR! We merge things in batches every few days, so this will probably sit around till the middle of next week before it is merged.

sure @CaseyCarter :-) , actually this was my first contribution to open source , will definitely improve.Thank you.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by AlexGuteniev** [comment]
@5AIPAVAN , can you undelete the branch? It is needed to be kept until the PR is merged

**Comment by 5AIPAVAN** [comment]
sorry @AlexGuteniev  doing it in 20 min. please keep me assigned

**Pull request closed without merging**
