### PR TITLE
Updated _MSVC_STL_UPDATE to November 2020

### LINKED ISSUE #1438: <yvals_core.h>: Update _MSVC_STL_UPDATE to November 2020
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/9959929c77b18e25b6dfbc8886e311b913321925/stl/inc/yvals_core.h#L505

Previous issue: #1338

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### PR DESCRIPTION
**Pull request by avinal**
Closes #1438

### CODE REVIEW

**Review by CaseyCarter — APPROVED** [review]
Looks good!

**Review by mnatsuhara — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Status update: we'll merge this soon. Currently we need to simultaneously merge changes on GitHub and our Microsoft-internal repo that exactly mirrors this (and builds the product that ships to customers); as this is a manual process, we batch up PRs in a "ready to merge" state to reduce the work needed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! :tada: :smile_cat:

**Comment by avinal** [comment]
Thanks @StephanTLavavej , I hope there will be more contributions soon 😁

**Pull request merged**
