### PR TITLE
syserror.cpp: add more matches against std::errc::timed_out

### LINKED ISSUE #2572: `<system_error>`: `WAIT_TIMEOUT` is not matched against by `std::errc::timed_out`
**Describe the bug**

If we look at https://github.com/microsoft/STL/blob/afe0800cd6bf0d163bf678ad4e1feb3c130d1ec5/stl/src/syserror.cpp#L104, we can see that errc::timed_out only matches against WSAETIMEDOUT and not against WAIT_TIMEOUT which is another common error code to indicate a timeout on Windows.

**Command-line test case**

repro.cpp

```
std::errc::timed_out == std::error_code { WAIT_TIMEOUT, std::system_category() };     // false
std::errc::timed_out == std::error_code { WAIT_TIMEOUT, std::generic_category() };     // false

std::make_error_condition(std::errc::timed_out) == std::error_code { WAIT_TIMEOUT, std::system_category() };     // false
std::make_error_condition(std::errc::timed_out) == std::error_code { WAIT_TIMEOUT, std::generic_category() };     // false
```

**Expected behavior**

`std::errc::timed_out` matches against WAIT_TIMEOUT when stored with the system category in an error code.

**STL version**

Latest commit on the main branch exhibits this behavior.

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2572 

This PR affects redist.

It is expected that the fix can be included in VS 2022 17.4 Preview 2. 

So this PR is blocked for now.

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I verified that these are documented system error codes (and that we aren't mixing unrelated error codes into this table).

* [System Error Codes (0-499)](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-)
  + **ERROR_SEM_TIMEOUT**
    - 121 (0x79)
    - The semaphore timeout period has expired.
  + **WAIT_TIMEOUT**
    - 258 (0x102)
    - The wait operation timed out.
* [System Error Codes (1300-1699)](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--1300-1699-)
  + **ERROR_TIMEOUT**
    - 1460 (0x5B4)
    - This operation returned because the timeout period expired.

**Comment by StephanTLavavej** [comment]
Marking as `blocked` - in theory we could merge this without waiting for 17.4 Preview 2 (as we've overcome our initial reluctance to merge redist-affecting changes, as long as coordinated header changes aren't necessary). However, since it's coming soon-ish, we may as well bundle this with #2742.

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for improving our list of error codes! :white_check_mark: :tada: :cat:

**Pull request merged**
