### PR TITLE
Accelerate tests by dividing them into shards

### PR DESCRIPTION
**Pull request by cbezault**

### CODE REVIEW

**Comment by cbezault** [comment]
I still don't get why pulling in the repos sometimes randomly takes 3 minutes.

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]
Looks good to me. There will be a trivial (adjacent lines) merge conflict with the `/analyze:autolog-` change. Also, we'll obviously need special handling due to the required checks changing.

I like how this scales neatly, instead of crudely dividing the tests into libcxx/std/tr1 batches.

**Comment by StephanTLavavej** [comment]
Trivial merge conflict in `azure-devops/run-build.yml`; GH-1394 modified `CMAKE_CXX_FLAGS` (adding `/analyze:autolog-`) next to this PR modifying `CMAKE_BUILD_TYPE` (adding `$(shardFlags)`).

**Comment by StephanTLavavej** [comment]
Thanks! For! Massively! Reducing! Test! Latency! By! Dividing! Them! Up! Into! Many! Slices!
:pizza: :pizza: :pizza: :pizza: :pizza: :pizza: :pizza: :pizza:

**Comment by cbezault** [comment]
It's always a joy coming back to old PRs and seeing thank you message puns I had missed.

**Pull request merged**
