### PR TITLE
Updated C++ latest working draft to N4988

### LINKED ISSUE #4881: `README.md`: Update working draft revision to N4988
[N4988](https://wg21.link/n4988) is the latest C++ working draft, it replaces [N4986](https://wg21.link/n4986).

Code:

https://github.com/microsoft/STL/blob/938bd5986189da29d45eaf2ba0053f1656cd54a3/README.md#L61

https://github.com/microsoft/STL/blob/938bd5986189da29d45eaf2ba0053f1656cd54a3/README.md#L572

Previous issue: #4842.

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by shaikhmudassir**
Resolve #4881

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Perfect, thank you!

We merge PRs simultaneously to our GitHub and MSVC-internal repos in a semi-manual process, batched up to save time. Your PR will be part of the next batch, very likely next week. I'll post comments here when I prepare your PR for merging!

**Review by frederick-vs-ja — APPROVED** [review]

**Review by fsb4000 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this important citation, and congratulations on your first microsoft/STL commit! :tada: :heart_eyes_cat: :scroll:

**Comment by shaikhmudassir** [comment]
Thank you. I look forward to contributing more in the future.

**Pull request merged**
