### PR TITLE
ignore rule-sets warning

### PR DESCRIPTION
**Pull request by steve02081504**
I clone the STL git repository locally and add it to my header path, but since I often have all the c++ rulesets open, the STL library headers become a big num of warnings in my project (providing 1000+ warnings) and I don't know how to ignore it.
This PR fixes that problem

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
This PR intends to suppress **40** kinds of warnings. However, none of the related problematic cases is described in the PR at this moment.

Are these warnings triggered within MSVC STL's headers? Have you tried to suppress them before including STL's headers and then unsuppress them after including?

**Comment by steve02081504** [comment]
> 

These warnings came after I directly included `STL\stl\inc` as one of the include file directories, STL headers from MSVC's install had no such problems
I do this because I want to always experience the latest STL files, but don't want to be overloaded with warnings that are not relevant to me
As for suppressing warnings before include and restoring them afterwards, that's a possible solution, but I feel it's a lot of hassle, especially when I rely on the STL for a lot of my own stuff and there's so much to change

**Comment by fsb4000** [comment]
Tests fail because https://github.com/microsoft/STL/issues/2908 , it is not related to your PR.

**Comment by steve02081504** [comment]
If anyone needs it, here are the details of stl's warning content
Sorry but it's in Chinese
[build.log](https://github.com/microsoft/STL/files/9505708/build.log)

**Comment by StephanTLavavej** [comment]
Thanks for looking into this! We talked about this at the weekly maintainer meeting - these warnings do appear to be largely spurious for the STL (for various reasons - e.g. we can't use the GSL because the GSL depends on us! :joy_cat:). However, we would want to individually verify that each of these warnings is definitely spurious before silencing them for the STL forever, and 40 warnings is a lot to look into.

We're going to close this PR without merging it, because we've already implemented a solution for projects like yours that are experiencing warnings in STL code. If you define `_STL_EXTRA_DISABLED_WARNINGS` project-wide to be a space-separated list of warning numbers, our machinery will *add* that to the list of warnings we always suppress. You can see the machinery here, right next to where your edits were:

https://github.com/microsoft/STL/blob/f9697fc439f863c444c729ad6ffbddd574797cda/stl/inc/yvals_core.h#L667-L669
https://github.com/microsoft/STL/blob/f9697fc439f863c444c729ad6ffbddd574797cda/stl/inc/yvals_core.h#L697-L708

Hope this helps!

**Pull request closed without merging**
