### PR TITLE
updated _MSVC_STL_UPDATE to November 2021

### LINKED ISSUE #2319: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to November 2021
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/ee5a216b516ef033d9153b324842369eee7653d1/stl/inc/yvals_core.h#L567

Previous issue: #2228

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### PR DESCRIPTION
**Pull request by SarveshLimaye**
Fixes #2319

### CODE REVIEW

**Review by CaseyCarter — APPROVED** [review]
Looks great, thanks!

**Review by StephanTLavavej — APPROVED** [review]

**Review by fsb4000 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Status update: We merge changes simultaneously to GitHub and our MSVC-internal repo. As this is a semi-manual process, we batch up PRs to save time. Your PR will be part of the next batch, likely in the next few days!

**Comment by SarveshLimaye** [comment]
@StephanTLavavej No problem. Thanks for the update. These good first issues are extremely helpful for new contributors like me 😄.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this macro, and congratulations on your first microsoft/STL commit! This will ship in VS 2022 17.1 Preview 3, and will almost certainly be the final value used for the 17.1 release. :tada: :rocket: :smile_cat:

**Pull request merged**
