### PR TITLE
Update contest.yaml

### PR DESCRIPTION
**Pull request by MyloCyrus**
*

### CODE REVIEW

**Comment by MyloCyrus** [comment]
I agree to be entered into the competition. I do not opt out. I am opted in and could win first place.

**Comment by MyloCyrus** [comment]
I authorize. Please switch my selection to soul proprietor, not
employer/employee, instead use Ira Higgins DBA.

**Comment by MyloCyrus** [comment]
I'm opting into the competition. Be advised please switch my selection to sole proprietor Ira Higgins DBA, not employee/employer.

**Comment by strega-nil-ms** [comment]
Spam - closing and locking.

**Pull request closed without merging**
