### PR TITLE
add info to workaround issue#981

### PR DESCRIPTION
**Pull request by fsb4000**
issue #981

I think that this information will be useful until the python test scripts are rewritten so that they can work with any active codepage.

If you have a better wording for this item then let me know.

### CODE REVIEW

**Comment by fsb4000** [comment]
python 3.9.5 broke the workaround :(

**Comment by fsb4000** [comment]
Changing Windows 10 user inteface to English helped with python 3.9.5. Tests passes...
interface

**Comment by fsb4000** [comment]
I found an another method.
If you have Visual Studio installed with only English language pack then tests passes without any manipulations with chcp or changing Windows user interface language.
(Previously I had 2 language packs installed: Russian and English)

**Comment by cpplearner** [comment]
Can we either fix the compiler warnings or change the script to decode the output with the current console code page?

**Review by MahmoudGSaleh — APPROVED** [review]

**Comment by fsb4000** [comment]
I experimented a little and realized that it was enough to change these settings  
`Settings and then: All Settings -> Time & Language -> Language -> "Administrative Language Settings" -> "Administrative" -> "Change system locale"`
to English. 
Windows 10 user inteface remains in the local language. 
изображение

So currently 2 working solutions:

1) Visual Studio installed with only English language pack

or

2) Change `Settings and then: All Settings -> Time & Language -> Language -> "Administrative Language Settings" -> "Administrative" -> "Change system locale"` to English.

But I think @cpplearner is right. We should fix it in the python scripts.
So I'm going to close this PR.
If someone will have a problem with the tests, then we can suggest these 2 solutions.

**Pull request closed without merging**
