### PR TITLE
Access _Clocptr statically, instead of through an instance

### PR DESCRIPTION
**Pull request by AtariDreams**

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks, and good catch! This is indeed static, and we're within the class itself here, so there's no reason to access it like a non-static data member:
https://github.com/microsoft/STL/blob/f9697fc439f863c444c729ad6ffbddd574797cda/stl/inc/xlocale#L217

**Review by AraHaan — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Also, I checked and this appears to be the only occurrence.

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for this code cleanup! :smile_cat: :smile_cat: :smile_cat:

**Pull request merged**
