### PR TITLE
Refactored declaring multiple variables on a single line

### LINKED ISSUE #522: STL: Avoid declaring multiple variables on a single line
In the STL, we conventionally avoid declaring multiple variables on a single line. That is:

```cpp
int cats, dogs; // we avoid this style

int meow; // we prefer this style
int woof;
```

Our reasons for this convention are:

1. Being aware of the variables in a class or function is important, because humans have difficulty reasoning about program state (especially when it's modifiable). Consistently declaring one variable per line makes it clear when variables are being introduced, and whether they're initialized. (It also makes it "feel costly" to declare many variables, which is subtle encouragement to avoid introducing unnecessary state.)
2. C++'s rules for multi-variable declarations are surprising to newer programmers. (In particular, the rules when pointers are involved.) Avoiding such declarations avoids the need to learn/teach/read that bit of complexity.

We're pretty consistent about following this convention, but there are a few files that should be changed. I observe the following occurrences (there may be more):

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/random#L622

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xiosbase#L511
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xiosbase#L532
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xiosbase#L540

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/cvt/wbuffer#L264

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/filesys.cpp#L317

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstol.cpp#L21

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoll.cpp#L19

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoul.cpp#L35-L36
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoul.cpp#L40

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoull.cpp#L27-L29
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xstoull.cpp#L31

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xxxprec.h#L70
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xxxprec.h#L105
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/src/xxxprec.h#L212

* These occurrences are weird-looking, but should be treated similarly:

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/iostream#L21-L29
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/iostream#L33-L41

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/ymath.h#L48
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/ymath.h#L56
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/ymath.h#L64

* Finally, the occurrences in `xcharconv_ryu.h` should **not** be changed at this time (as this code is kept in sync with the upstream Ryu project):

https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xcharconv_ryu.h#L1061
https://github.com/microsoft/STL/blob/fffbd8fe05cd1a21adf2284eb6acef69e982b3c7/stl/inc/xcharconv_ryu.h#L1751

I found all of these occurrences by using VSCode to regex-search for `(\w+)(, \*?\w+)+;` excluding files in `tests/*`.

### PR DESCRIPTION
**Pull request by JeanPhilippeKernel**
# Description

Fixes #522.

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Are the `llvm-project` bits changes intentional?

**Comment by JeanPhilippeKernel** [comment]
Oop nope:( ! I think It changed when I pulled from STL/master to mine

**Comment by JeanPhilippeKernel** [comment]
Oh great !! Thank you so much for the technique !!! 
I was looking for a way to do something like that !

**Comment by BillyONeal** [comment]
If you aren't transferring between repos the diff/apply step can be reduced reset, assuming you are already on your branch that you're trying to submit:

```
    git fetch
    git merge origin/master
    git submodule update
    git reset origin/master
    git commit -am "GH-550 Refactored declaring multiple variables on a single line"
````

**Comment by StephanTLavavej** [comment]
@JeanPhilippeKernel - thanks for improving the codebase yet again. :-)

@BillyONeal - oh, that makes even more sense, thanks for teaching us.

**Comment by JeanPhilippeKernel** [comment]
It's my pleasure and I feel so honored to work with y'all :)
you're an amazing team !! I learn a lot !

**Pull request merged**
