### PR TITLE
Corrected URI to URL

### PR DESCRIPTION
**Pull request by rithikmali**
Please note that acceptance of community PRs will be delayed while we are
bringing our test and CI systems online. For more information, see the
README.md.

# Description
On line 157 of README. md, corrected URI to URL. 
# Checklist:

- [x] I understand README.md.
- [x] If this is a feature addition, that feature has been voted into the C++
  Working Draft.
- [ ] Identifiers in any product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 .
- [x] Identifiers in test code changes are *not* `_Ugly`.
- [x] Test code includes the correct headers as per the Standard, not just
  what happens to compile.
- [ ] The STL builds and test harnesses have passed (must be manually verified
  by an STL maintainer before CI is online, leave this unchecked for initial
  submission).
- [x] This change introduces no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate or
  trivially copyable, etc.). If unsure, leave this box unchecked and ask a
  maintainer for help.

### CODE REVIEW

**Comment by BillyONeal** [comment]
Why is this a "correction"? (It's both a URI and a URL)

**Comment by StephanTLavavej** [comment]
While both are correct here, I prefer URL because it’s more specific and more commonly heard. What are the reasons to prefer URI?

**Comment by BillyONeal** [comment]
Only resistance to changing things, as AFAIK those terms are usually interchangable even though technically URI is a bigger namespace.

/azp run

**Comment by BillyONeal** [comment]
(TIL Azure Pipelines commands need to be their own comment)

**Pull request merged**
