### PR TITLE
<yvals_core.h>: Updated _MSVC_STL_UPDATE to September 2020

### PR DESCRIPTION
**Pull request by Madhvan28**

### CODE REVIEW

**Comment by Madhvan28** [comment]
#1257 solved

**Review by miscco — APPROVED** [review]
Thanks, and congratulations to your first submission

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
We'll be merging this soon - we have to merge PRs simultaneously on GitHub and our MSVC-internal repo, so we batch them up, and CppCon this week has kept us unusually busy!

**Comment by CaseyCarter** [comment]
Thanks, and 🎉🎉🎉 congratulations on your first STL contribution! 🎉🎉🎉

**Pull request merged**
