### PR TITLE
Revert "Add diagnostics for sporadic failures in a `<format>` test"

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Reverts microsoft/STL#2494

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
@barcharcraz would like for this to be merged some time after #2569. (Perhaps one or two weeks?)

**Review by CaseyCarter — APPROVED** [review]

**Comment by AlexGuteniev** [comment]
Maybe not so fast then? We've seen the failure three times in three months.

**Comment by StephanTLavavej** [comment]
I think one month would be plenty (personally I'd be happy with 2 weeks). The diagnostics don't change the test coverage, they just make investigation easier.

**Comment by StephanTLavavej** [comment]
Charlie said he's happy with 2 weeks, so Feb 28 or later. Moving to Ready To Merge so we'll pick this up in the next batch (I don't anticipate merging on Thu/Fri).

**Review by barcharcraz — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for removing this temporary machinery! :gear: :white_check_mark: :tada:

**Pull request merged**
