### PR TITLE
Documentation Fix for #3780

### LINKED ISSUE #3780: Clean up comments for LWG-3912 `enumerate_view::iterator::operator-` should be `noexcept`
LWG-3912 has been voted into the standard, so we should remove the following `/* strengthened */` comment.

Code:

https://github.com/microsoft/STL/blob/15aea9852b557f70821651600e51d9a2b3b1a95e/stl/inc/ranges#L6126-L6129

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### PR DESCRIPTION
**Pull request by JacobOgle**
Fix #3780

### CODE REVIEW

**Review by frederick-vs-ja — CHANGES_REQUESTED** [review]
Thanks!
However, it would be better to write `Fix #3780` in the description of this PR, which will automatically tell Github that this PR will resolve the mentioned issue.

**Comment by JacobOgle** [comment]
@frederick-vs-ja apologies for the error! I just fixed the description to match the request. Let me know if anything else is needed!

**Review by frederick-vs-ja — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this comment - and congratulations on your first microsoft/STL commit! :tada: :heart_eyes_cat: :rocket:

This change will ship in VS 2022 17.8 Preview 1.

**Pull request merged**
