### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by EternalCoderss**

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
You shall be aware of that MSVC STL is more than "Standard Template Library".

The "natural continuation" of the original SGI STL is a large part of MSVC STL, but not same as it.

**Comment by fsb4000** [comment]
CI fails because:
```
This is the official repository for Microsoft's implementation of the C++ Standard Template Library (also known as the STL),
``` 
is 125 characters long but we have limit 120.

**Review by CaseyCarter — COMMENTED** [review]
We refer to MSVC's implementation of the C++ Standard Library as "the STL". This is not a precise naming, since the library that was the Standard Template Library nearly three decades is only a small part of the C++ Standard Library. Referring to our entire implementation as "the STL" is an instance of metonymy, ["the substitution of the name of an attribute or adjunct for that of the thing meant"](https://www.google.com/search?q=metonymy&rlz=1C1GCEU_enUS924US925&sxsrf=ALiCzsakPKQ6EdxP9qxkTcXI3mTOogutQQ%3A1659416178092&ei=cq7oYp6aBdHw9AOiw53AAg&ved=0ahUKEwiem9H-rqf5AhVROH0KHaJhBygQ4dUDCA4&uact=5&oq=metonymy&gs_lcp=Cgdnd3Mtd2l6EAMyBAgjECcyBQgAEJECMgUIABCRAjIFCAAQkQIyCAgAEIAEELEDMgsIABCABBCxAxCDATIFCAAQgAQyBQgAEIAEMgUIABCABDIFCAAQgAQ6BwgAEEcQsAM6BwgjELECECc6BwgAELEDEAo6CggAELEDEIMBEAo6BAgAEApKBAhBGABKBAhGGABQqAlYiQpgtAtoAXABeACAAU-IAZIBkgEBMpgBAKABAcgBCMABAQ&sclient=gws-wiz), like calling business executives "suits" or motorcycles "bikes".

I don't think this change is appropriate.

**Comment by StephanTLavavej** [comment]
Thanks for submitting this pull request! However, I believe that the current wording should stand, as it represents a compromise between viewpoints.

"C++ Standard Library" is the officially correct term. See WG21-N4910 16.1 [library.general]/1 "This Clause describes the contents of the *C++ standard library*". We acknowledge this by making it the section title, and putting it first in the explanation.

"(also known as the STL)" is the shorthand that we routinely use, as implementers have the sovereign right to name what they work on. We acknowledge this by making it the repo name.

It's true that the "STL" [metonymy](https://en.wikipedia.org/wiki/Metonymy) involves the historical Standard Template Library, but it shouldn't be necessary to devote readme space to explaining this. The thinking was that this is widely known, and not a source of confusion. As @frederick-vs-ja noted, attempting to explain the full story brings in a *lot* of detail.

**Comment by StephanTLavavej** [comment]
Closing this PR - again, thanks for submitting it, even though we've decided not to merge it.

**Pull request closed without merging**
