### PR TITLE
Untag dispatch `<xstring>`

### PR DESCRIPTION
**Pull request by AlexGuteniev**
Towards #189

Same as #2479, nothing to see here

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
I have pushed a commit to undo an unintentional submodule change, which should allow the tests to pass.

**Comment by AlexGuteniev** [comment]
https://github.com/microsoft/STL/issues/189#issuecomment-1073070153 can be hidden after this change

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Looks great, thanks for the continued `if constexpr`ization!

I pushed a trivial change to remove `// general algorithm` comments (matching your previous `_Traits_find_first_of()` change) - these were the counterparts of the `// special case for std::char_traits` comments, and both are no longer necessary now that there's a clear `if constexpr (_Special) { ... } else { ... }`. 

Note to reviewers: as before, GitHub makes this diff look way worse than it really is. I copied each pair of old and new implementations into VS Code editors, then reordered the old overloads so that the "special" case occurs first. Along with a bit of indentation, this made the diff easy to read.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by raghavthind2005 — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for completing the untag dispatching of `<xstring>`'s find functions and improving throughput! :rocket: :rabbit2: :stopwatch:

**Pull request merged**
