### PR TITLE
Fix #379: <complex>: asinh(-1e+307 + 2e+307i) is wrong

### LINKED ISSUE #379: <complex>: asinh(-1e+307 + 2e+307i) is wrong
**Describe the bug**
Results of the following are wrong:
```
asinh(-1e+307 + 2e+307i)
acosh(-1e+307 + 2e+307i)
acos(2e+307 + 1e+307i)
acos(-2e+307 + 1e+307i)
```

**Command-line test case**
Visual Studio 16.4.1:

```
G:\Temp>type asinh.cpp
#include <complex>
#include <cstdio>

int main() {
    using namespace std;
    const auto a = asinh(-1e+307 + 2e+307i);
    const auto b = acosh(-1e+307 + 2e+307i);
    const auto c = acos(2e+307 + 1e+307i);
    const auto d = acos(-2e+307 + 1e+307i);

    puts("asinh(-1e+307 + 2e+307i)");
    puts("  Expected: (-708.39148968594902047...,1.1071487177940905030...)");
    printf("    Actual: (%.17g,%.17g)\n", a.real(), a.imag());

    puts("acosh(-1e+307 + 2e+307i)");
    puts("  Expected: (708.39148968594902047...,2.0344439357957027354...)");
    printf("    Actual: (%.17g,%.17g)\n", b.real(), b.imag());

    puts("acos(2e+307 + 1e+307i)");
    puts("  Expected: (0.4636476090008061162...,-708.39148968594902047...)");
    printf("    Actual: (%.17g,%.17g)\n", c.real(), c.imag());

    puts("acos(-2e+307 + 1e+307i)");
    puts("  Expected: (2.6779450445889871222...,-708.39148968594902047...)");
    printf("    Actual: (%.17g,%.17g)\n", d.real(), d.imag());
}

G:\Temp>cl /EHsc /W4 asinh.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.24.28314 版
版权所有(C) Microsoft Corporation。保留所有权利。

asinh.cpp
Microsoft (R) Incremental Linker Version 14.24.28314.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:asinh.exe
asinh.obj

G:\Temp>.\asinh.exe
asinh(-1e+307 + 2e+307i)
  Expected: (-708.39148968594902047...,1.1071487177940905030...)
    Actual: (708.27991791029194,1.1071487177940904)
acosh(-1e+307 + 2e+307i)
  Expected: (708.39148968594902047...,2.0344439357957027354...)
    Actual: (-707.58677072973205,2.0344439357957027)
acos(2e+307 + 1e+307i)
  Expected: (0.4636476090008061162...,-708.39148968594902047...)
    Actual: (0.46364760900080615,-0.74737784215813008)
acos(-2e+307 + 1e+307i)
  Expected: (2.6779450445889871222...,-708.39148968594902047...)
    Actual: (2.677945044588987,708.27991791029194)
```

**Additional context**
https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/complex#L1380

Should be `_Beta = -_Zr - _Wr * (_Zi / _Alfa);`

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/complex#L1305

Should be `_Beta = _Wr * (_Zr / _Alfa) + _Zi;`

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/complex#L1234

Should be `_Beta = _Wr * (_Zi / _Alfa) - _Zr;`

https://github.com/microsoft/STL/blob/aa0a7a3d859ade0f6f1ff13aa4ef74b3d5ce2326/stl/inc/complex#L1242

Should be `if (0 <= _Vx) {`

### PR DESCRIPTION
**Pull request by statementreply**
# Description

Fix a few wrong formula (possibly typo) in complex asinh, acosh and acos. (#379)

# Checklist

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [x] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

**Comment by BillyONeal** [comment]
@stwish-msft Do we need to make corresponding changes to the UCRT?

**Comment by statementreply** [comment]
> @stwish-msft Do we need to make corresponding changes to the UCRT?

I found another correctness bug in UCRT complex (but not in STL) during testing. I didn't report that bug in #379 because I believed this is not the place to report UCRT bugs.

```
G:\Temp>type ahyp2.cpp
#include <complex>
#include <complex.h>
#include <cstdio>

int main() {
    using namespace std;
    const auto e_stl = asinh(2.0i);
    const auto e_ucrt = casinh(_Cbuild(0.0, 2.0));

    puts("asinh(2.0i)");
    puts("  Expected: ( 1.3169578969248167086..., 1.5707963267948966192...)");
    printf("  STL     : (% -25.17g,% -25.17g)\n", e_stl.real(), e_stl.imag());
    printf("  UCRT    : (% -25.17g,% -25.17g)\n", creal(e_ucrt), cimag(e_ucrt));
}

G:\Temp>cl /std:c++14 /EHsc /W4 ahyp2.cpp
用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.24.28314 版
版权所有(C) Microsoft Corporation。保留所有权利。

ahyp2.cpp
Microsoft (R) Incremental Linker Version 14.24.28314.0
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:ahyp2.exe
ahyp2.obj

G:\Temp>.\ahyp2
asinh(2.0i)
  Expected: ( 1.3169578969248167086..., 1.5707963267948966192...)
  STL     : ( 1.3169578969248166      , 1.5707963267948966      )
  UCRT    : ( 0                       , 1.5707963267948966      )
```

**Comment by BillyONeal** [comment]
You are correct that this isn't the place for UCRT bugs, but the implementations are similar -- I believe they both came from Dinkumware once upon a time, so when one is broken, usually they both are.

**Comment by StephanTLavavej** [comment]
Can you provide test values that exercise each of the altered lines?

**Comment by statementreply** [comment]
> Can you provide test values that exercise each of the altered lines?

Assuming 64-bit `long double`

## L1234

```
assert(nearly_equal(acos(-2e+307 + 1e+307i), 2.677945044588987 - 708.3914896859491i);
assert(nearly_equal(acos(-4e+37f + 2e+37if), 2.6779451f - 87.386663if);
assert(nearly_equal(acos(-2e+307L + 1e+307il), 2.677945044588987L - 708.3914896859491il);
```

## L1242

```
assert(nearly_equal(acos(2e+307 + 1e+307i), 0.4636476090008061 - 708.3914896859491i);
assert(nearly_equal(acos(4e+37f + 2e+37if), 0.4636476f - 87.386663if);
assert(nearly_equal(acos(2e+307L + 1e+307il), 0.4636476090008061L - 708.3914896859491il);
```

## L1305

```
assert(nearly_equal(acosh(-1e+307 + 2e+307i), 708.3914896859491 + 2.0344439357957027i));
assert(nearly_equal(acosh(-2e+37f + 4e+37if), 87.386663f + 2.0344439if));
assert(nearly_equal(acosh(-1e+307L + 2e+307il), 708.3914896859491L + 2.0344439357957027il));
```

## L1380

```
assert(nearly_equal(asinh(-1e+307 + 2e+307i), -708.3914896859491 + 1.1071487177940904i));
assert(nearly_equal(asinh(-2e+37f + 4e+37if), -87.386663f + 1.1071488if));
assert(nearly_equal(asinh(-1e+307L + 2e+307il), -708.3914896859491L + 1.1071487177940904il));
```

**Comment by BillyONeal** [comment]
Hello @statementreply!

I'm seeing that the new implementation doesn't pass the test cases you enumerated above assuming nearly_equal_partwise tests that the results are within +/- 1 ULP. e.g. `nearly_equal_partwise(acos(4e+37f + 2e+37if), 0.4636476f - 87.386663if)` is off by 2 ULP. I observe that the complex implementation calls several base transcendentals that each individually have a +/- 1 ULP policies which can lead to this outcome; is that expected?

Thanks again for your contribution!

**Comment by StephanTLavavej** [comment]
That seems expected to me; if you're concerned about the 2 ULP differences, I recommend filing an issue to investigate later.

**Comment by BillyONeal** [comment]
I still would like to give @statementreply a couple days to comment in case (s)he wants to before merging just in case the results I observe are unexpected.

**Comment by statementreply** [comment]
@BillyONeal That's expected. This PR fixes some coding errors in the original implementation (which doesn't guarantee +/- 1 ULP accuracy) of `asinh`, `acosh` and `acos`. I don't intend to improve their accuracy in this PR.

**Comment by BillyONeal** [comment]
Sounds good, thanks again for your contribution!

**Comment by StephanTLavavej** [comment]
This is a great example of a bug that we would have had a much harder time fixing before open-source! We really appreciate your analysis, test cases, and fix. 😸

**Pull request merged**
