### PR TITLE
Fix #842 "GitHub: Workflow automation is failing".

### LINKED ISSUE #842: GitHub: Workflow automation is failing
After merging #829, the workflow automation failed on #841, emitting:

```
2020-05-16T22:32:19.9566249Z ##[group]Run alex-page/github-project-automation-plus@v0.2.3
2020-05-16T22:32:19.9566599Z with:
2020-05-16T22:32:19.9566822Z   project: Code Reviews
2020-05-16T22:32:19.9566979Z   column: New
2020-05-16T22:32:19.9567183Z ##[endgroup]
2020-05-16T22:32:20.9064452Z ##[error]Parameter token or opts.auth is required
```

### PR DESCRIPTION
**Pull request by StephanTLavavej**
Revert "Use a GitHub Workflow to automate Code Reviews Project (#829)"

This reverts commit ed2ba34997f80de477859a7637e33d4fa2fa001d.

We discovered that what we wanted to do simply isn't possible with GitHub workflows: https://github.com/microsoft/STL/issues/842#issuecomment-630367950

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Thanks, I didn't realize that Power Word: Fix works only in the description, not the title :smiley_cat:

**Comment by cbezault** [comment]
If you look at the issue it links to this PR from the title but this PR doesn't link to the issue. Very weird.

**Comment by AlexGuteniev** [comment]
Was invisible part (secret removal) also made?

**Comment by StephanTLavavej** [comment]
Thanks for the reminder! I went ahead and removed it just now.

**Pull request merged**
