### PR TITLE
<fstream>: fix(?) tellg

### LINKED ISSUE #2477: `<fstream>`: Potential glitch with `ifstream::peek` in text mode when the file contains LF line endings
Originally reported as DevCom-1628547 and internal VSO-1458783 / AB#1458783 .

```
C:\Temp>type meow.cpp
```
```cpp
#include <cassert>
#include <fstream>
#include <iostream>
using namespace std;

int main() {
    const char* const filename = "example_file.txt";

    {
        ofstream o(filename, ios_base::binary);
        assert(o.good());
        o << "cute fluffy kittens\n";
    }

    ifstream fin(filename);
    assert(fin.good());
    cout << "start pos: " << fin.tellg() << '\n';
    assert(fin.good());
    cout << "fin.peek(): " << static_cast<char>(fin.peek()) << '\n';
    assert(fin.good());
    cout << "end pos (expected 0): " << fin.tellg() << '\n';
}
```
```
C:\Temp>cl /EHsc /nologo /W4 meow.cpp
meow.cpp

C:\Temp>meow
start pos: 0
fin.peek(): c
end pos (expected 0): -1
```

I don't know whether this is by design.

### PR DESCRIPTION
**Pull request by fsb4000**
Fixes #2477 

It seems that case not thought out by fgetpos developers.

from `fgetpos.cpp`
```C++
// Gets the file position in the internal fpos_t format.  The returned value
// should only be used in a call to fsetpos().  Our implementation happens to
// just wrap _ftelli64() and _fseeki64().  Return zero on success; returns -1
// and sets errno on failure.
extern "C" int __cdecl fgetpos(FILE* const stream, fpos_t* const position)
```
and the docs say the same: https://learn.microsoft.com/ru-ru/cpp/c-runtime-library/reference/fgetpos?view=msvc-170

>If successful, fgetpos returns 0. On failure, it returns a nonzero value and sets errno to one of the following manifest constants (defined in STDIO.H): EBADF, which means the specified stream is not a valid file pointer or is not accessible, or EINVAL, which means the stream value or the value of pos is invalid, such as if either is a null pointer

But when we have such text file with `\n` but without `\r`, fgetpos goes to the end like everything is fine but returns -1.

I found this:

1) ftell.cpp, line 145.
```c++
// This function handles the extra adjustments that need to be made to the file
// position returned by ftell when a stream is opened in read mode.
static __int64 __cdecl common_ftell_read_mode_nolock(
```

later in the function:
```c++
    // Seek to the end of the file.  If the current position is the end of the
    // file, then scan the buffer for newlines and adjust bytes_read:
    if (_lseeki64_internal(fh, 0, SEEK_END, ptd) == lowio_position)
    {
        bytes_read += count_newline_bytes(stream->_base, stream->_base + bytes_read, text_mode);

        // If the last byte was a ^Z, that character will not be present in the
        // buffer (it is omitted by lowio):
        if (stream.ctrl_z())
        {
            bytes_read += buffer_character_size(text_mode);
        }
    }
```
So they don't expect `\n` without '\r' at all and `count_newline_bytes` adds extra 1 byte. 
Do they need to fix `count_newline_bytes` to actually check `\r`?

And return value:
```c++
// lowio_position = 20
// bytes_read = 21
// translation_factor = 1
// buffer_offset = 0
return lowio_position
        - (bytes_read    / translation_factor)
        + (buffer_offset / translation_factor);
```

Anyway we can pretend that if `errno` is not set then everything is fine.

### CODE REVIEW

**Comment by fsb4000** [comment]
My solution will not work for something like this:
```c++
#include <cassert>
#include <fstream>
#include <iostream>
using namespace std;

int main() {
    const char* const filename = "example_file.txt";

    {
        ofstream o(filename, ios_base::binary);
        assert(o.good());
        o << "cute fluffy kittens\n\n\n";
    }

    ifstream fin(filename);
    assert(fin.good());
    assert(fin.tellg() == 0);
    assert(fin.good());
    assert(static_cast<char>(fin.get()) == 'c');
    assert(fin.good());
    assert(static_cast<char>(fin.get()) == 'u');
    assert(fin.good());
    assert(static_cast<char>(fin.get()) == 't');
    assert(fin.good());
    assert(fin.tellg() == 3);
}
```
😿

**Comment by fsb4000** [comment]
So should I create a Devcom ticket for UCRT team?
```c++
#define _CRT_SECURE_NO_WARNINGS
#include <assert.h>
#include <stdio.h>

int main() {
    const char* const filename = "example_file.txt";

    {
        FILE* file = fopen(filename, "wb");
        assert(file != NULL);

        const char* const str = "cute fluffy kittens\n\n";
        const int SIZE = 23;
        const int write_count = fwrite(str, sizeof(char), SIZE, file);
        assert(write_count == SIZE);
        fclose(file);
    }

    FILE* file = fopen(filename, "r");
    assert(file != NULL);
    fgetc(file);
    long int pos = ftell(file); 
    // ftell's docs: "File position indicator on success or -1L if failure occurs."
    //assert(pos != -1L);
    printf("pos: %ld\n", pos); // prints "pos: -1"
}
```

**Comment by fsb4000** [comment]
mingw-w64 also prints -1 for C version but libstdc++ somehow could print the correct result for C++ version.

libc++ prints 0 if buffering is used( and they use buffering by default) but prints -1 if stream is unbuffered.

 I created https://github.com/llvm/llvm-project/issues/57946

**Comment by StephanTLavavej** [comment]
From a brief glance at this issue, it does seem that this is a UCRT bug that should be reported, then we can cite the bug number as TRANSITION if we choose to work around it.

**Comment by fsb4000** [comment]
Yes, I created: https://developercommunity.visualstudio.com/t/10166673

I also found the same issue about `ftell` and Linux line endings: https://developercommunity.visualstudio.com/t/425878 and it is closed 😿

**Pull request closed without merging**
