### PR TITLE
`<vector>`: Apply append-and-rotate for `vector<bool>` insertion

### LINKED ISSUE #3007: `<vector>`: `vector<bool>::insert(where, first, last)` has forbidden complexity for input iterators
https://github.com/microsoft/STL/blob/2263d931f48a4e196036b2523af7a0048bb96b46/stl/inc/vector#L3147-L3149

When we're given input-only iterators, this repeatedly mid-inserts, shifting down existing elements to make room. That's O((last - first) * (vb.end() - where)), which is forbidden by WG21-N4910 [vector.modifiers]/1:

> *Complexity:* If reallocation happens, linear in the number of elements of the resulting vector; otherwise, linear in the number of elements inserted plus the distance to the end of the vector.

Which applies to `vector<bool>` too, [vector.bool]/2:

> Unless described below, all operations have the same requirements and semantics as the primary `vector` template, except that operations dealing with the `bool` value type map to bit values in the container storage and `allocator_traits::construct` (20.2.8.3) is not used to construct these values.

It's *extra* horrible because each insertion is performing a ton of bitwise work to shift the packed elements down by 1 bit.

Will also affect `vector<bool>::insert_range(where, range)` after merging #2806.

---

Note that `vector<T>` is unaffected because it appends followed by rotating the elements into place:

https://github.com/microsoft/STL/blob/2263d931f48a4e196036b2523af7a0048bb96b46/stl/inc/vector#L1046-L1070

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Fixes #3007.

### CODE REVIEW

**Review by strega-nil-ms — COMMENTED** [review]
This LGTM!

**Review by strega-nil-ms — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! FYI @strega-nil-ms, I pushed minor changes after you approved.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this performance bug that was so bad it became a correctness bug!

### :lady_beetle:
## :lady_beetle:
# :lady_beetle:

**Pull request merged**
