### PR TITLE
Remove outdated `#if` guard

### PR DESCRIPTION
**Pull request by cpplearner**
DevCom-952724 is "Fixed In: Visual Studio 2022 version 17.0".

### CODE REVIEW

**Review by CaseyCarter — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Changing labels as this is a test-only change.

**Review by fsb4000 — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Resolved trivial merge conflict (the deleted line here wins).

**Comment by StephanTLavavej** [comment]
Thanks for finding this and cleaning it up! :broom: :tada: :smile_cat:

**Pull request merged**
