### PR TITLE
Status Chart: Weekly update

### PR DESCRIPTION
**Pull request by StephanTLavavej**
This also updates the Node.js version in the README due to a security update.

Live preview: [stephantlavavej.github.io/STL/](https://stephantlavavej.github.io/STL/)
===

### CODE REVIEW

**Comment by statementreply** [comment]
Should we add C++23 features to the chart now, or after finishing implementing C++20?

**Comment by StephanTLavavej** [comment]
I could add an off-by-default line for C++23; that's very little work. (Mostly, choosing a color.)

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
> I could add an off-by-default line for C++23; that's very little work. (Mostly, choosing a color.)

I wouldn't mind having the line on-by-default.

**Comment by StephanTLavavej** [comment]
Ok - I'll work on that for next week's update!

**Pull request merged**
