### PR TITLE
`<ranges>`: Fix formatting ranges for ADL-only ranges

### PR DESCRIPTION
**Pull request by hewillk**
This is the followup of #5173.

### CODE REVIEW

**Comment by hewillk** [comment]
Sorry, how do I format the code? I don't have a rep, I'm just editing it on the GitHub web.

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
> Sorry, how do I format the code? I don't have a rep, I'm just editing it on the GitHub web.

For future reference, you can click "details" on the STL-CI check, click the link on that page to get to the Azure pipeline run:

image

There will be 1 attached artifact:

image

which is a patch with format corrections:

```diff
diff --git a/stl/inc/format b/stl/inc/format
index 2b7aa8c..6026f34 100644
--- a/stl/inc/format
+++ b/stl/inc/format
@@ -3271,7 +3271,7 @@ void _Range_formatter_format_as_sequence(const formatter<_Ty, _CharT>& _Underlyi
     auto _Iter       = _RANGES begin(_Rng);
     const auto _Sent = _RANGES end(_Rng);
     for (; _Iter != _Sent; ++_Iter) {
-        auto&& _Elem  = *_Iter;
+        auto&& _Elem = *_Iter;
         if (_Separate) {
             _Ctx.advance_to(_STD _Fmt_write(_Ctx.out(), _Separator));
         }
```

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
We should add test coverage for this, but it's not critical enough to push changes to the PR and possibly trip the de minimis threshold for the CLA (if you haven't signed it yet - I haven't checked). We're unlikely to mess with this again in the short term, so the risk is low. I've added a personal todo to follow up here.

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for fixing this bug in one of our newest and soon-to-be-popular features! :hammer_and_wrench: :lady_beetle: :four:

**Pull request merged**
