### PR TITLE
Update _MSVC_STL_UPDATE to March 2021

### LINKED ISSUE #1707: <yvals_core.h>: Update _MSVC_STL_UPDATE to March 2021
Explanation on our wiki: [Macro `_MSVC_STL_UPDATE`](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code:
https://github.com/microsoft/STL/blob/30ac4400e528e9837f2e8d9867da668b0de3f7eb/stl/inc/yvals_core.h#L518

Previous issue: #1618

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! :smile_cat:

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

### PR DESCRIPTION
**Pull request by hatcat**
Closes #1707.

### CODE REVIEW

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks! We have a two-review process (even for one-line changes :joy_cat:) so I'll find a second maintainer to approve and then this will be ready to merge. I was just about to prepare a batch of merges for VS 2019 16.10 Preview 2 so I can add your change.

A couple of logistical issues:

* GitHub is surprisingly picky about the close/fix/resolve syntax - you have to say the magic words in the PR description. They have no effect in the PR title; in commit messages they create "mentions" but not the connection that makes the PR auto-close the issue. I've edited your PR description, and now the issue appears in the "Linked issues" section of the sidebar.
* I've edited the PR title to be descriptive; this makes it easier to see what PRs are doing when we have 20+ of them open (see the [Code Reviews project](https://github.com/microsoft/STL/projects/1?fullscreen=true) for what that looks like).

**Comment by hatcat** [comment]
Many thanks for your clarification. I hope to make further contributions (including the Linear Algebra proposal when it finally makes its way out of LEWG, LWG and plenary, which will be about 2027 at this rate...) so I will be keeping abreast of the rules. I suppose I should read the wiki too...!

**Review by CaseyCarter — APPROVED** [review]
Hey, Guy - welcome to the STL!

**Comment by StephanTLavavej** [comment]
Thanks for updating this version number; it'll ship in VS 2019 16.10 Preview 2. Congratulations on your first microsoft/STL commit! :tada: :partying_face: :smile_cat:

**Pull request merged**
