### PR TITLE
Change _MSVC_STL_UPDATE to June 2023

### PR DESCRIPTION
**Pull request by tungbq**
Closes: #3741

### CODE REVIEW

**Review by fsb4000 — APPROVED** [review]
Your patch is good!
The test suite failed for some unknown reason.
I pinged the Microsoft developers. 
They will rerun the pipeline later.
You don't need to do anything.

**Comment by fsb4000** [comment]
изображение
We have the same timezone!

**Review by CaseyCarter — APPROVED** [review]

**Comment by CaseyCarter** [comment]
Looks great! I kicked the stalled test so it should run to completion now.

FYI, our process is to merge things in batches, so once a second maintainer approves this will sit for a few days before being merged as part of a batch. Congratulations on your first STL contribution!

**Review by StephanTLavavej — APPROVED** [review]

**Comment by tungbq** [comment]
Thank you all for reviewing and collaboration!

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! :tada: :rocket: :heart_eyes_cat:

**Pull request merged**
