### PR TITLE
Casey's latest misc branch

### PR DESCRIPTION
**Pull request by CaseyCarter**
Some drive-bys.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
You have no power here, Gandalf the Grey!

https://github.com/microsoft/STL/blob/926d458f82ae1711d4e92c0341f541a520ef6198/azure-pipelines.yml#L9-L10

**Comment by CaseyCarter** [comment]
> You have no power here, Gandalf the Grey!
> 
> https://github.com/microsoft/STL/blob/926d458f82ae1711d4e92c0341f541a520ef6198/azure-pipelines.yml#L9-L10

Yes, I noticed. I deserve this for trying to be lazy.

**Pull request closed without merging**
