### PR TITLE
Implement LWG-3701: Make `formatter<remove_cvref_t<const charT[N]>, charT>` requirement explicit

### LINKED ISSUE #2953: LWG-3701 Make `formatter<remove_cvref_t<const charT[N]>, charT>` requirement explicit
LWG-3701 Make `formatter<remove_cvref_t<const charT[N]>, charT>` requirement explicit

### PR DESCRIPTION
**Pull request by strega-nil-ms**
Fixes #2953

### CODE REVIEW

**Review by miscco — APPROVED** [review]

**Review by CaseyCarter — CHANGES_REQUESTED** [review]
Nitpicky change. I think it's reasonable that we don't have new test coverage. Since we're enforcing a better requirement than what the standard specifies, the problem cited in the issue isn't a problem for us (https://godbolt.org/z/dsoMseMnh).

**Review by CaseyCarter — APPROVED** [review]

**Review by frederick-vs-ja — APPROVED** [review]
No change requested. I guess we can test this with the (duplicate of) `std::formattable` concept added by [P2286R8](https://wg21.link/p2286r8). But since this will be tested alongwith P2286R8, it may be not worth to duplicate such test.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for implementing another LWG issue resolution! :chart_with_downwards_trend: :heart_eyes_cat: :white_check_mark:

**Pull request merged**
