### PR TITLE
Updated _MSVC_STL_UPDATE to July 2024

### LINKED ISSUE #4752: `<yvals_core.h>`: Update `_MSVC_STL_UPDATE` to July 2024
Explanation on our wiki: [Macro _MSVC_STL_UPDATE](https://github.com/microsoft/STL/wiki/Macro-_MSVC_STL_UPDATE)

Code: https://github.com/microsoft/STL/blob/165fc9459c85faa65cd3dec313eb10f55bab154c/stl/inc/yvals_core.h#L891

Previous issue: #4704

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### PR DESCRIPTION
**Pull request by ravixalgorithm**
resolves #4752

### CODE REVIEW

**Comment by AlexGuteniev** [comment]
Hi.

Your PR title is too low-level. The revision and line information can be later fetched from history if neccessary.
Instead, please focus on plain English description on what is done.

Also, the description should mention "resolves #issue", it is not neccessary for the commit itself, but should be in the description.

And you should use the **issue** number, not the **line** number,

**Comment by ravixalgorithm** [comment]
> _ No description provided. _
resolves STL/stl/inc/yvals_core.h Line 891 in 165fc94

**Comment by ravixalgorithm** [comment]
> Hi.
> 
> Your PR title is too low-level. The revision and line information can be later fetched from history if neccessary. Instead, please focus on plain English description on what is done.
> 
> Also, the description should mention "resolves #issue", it is not neccessary for the commit itself, but should be in the description.
> 
> And you should use the **issue** number, not the **line** number,



Is it Correct now??

**Comment by ravixalgorithm** [comment]
Can Anyone please review this code pls ..

**Comment by AlexGuteniev** [comment]
> Is it Correct now??

Almost. What you put in the **title** should go in the **description**, which is still empty. The title should decribe the change in high level plaintext.

**Comment by ravixalgorithm** [comment]
> > Is it Correct now??
> 
> Almost. What you put in the **title** should go in the **description**, which is still empty. The title should decribe the change in high level plaintext.

I think its now good or can you suggest me a title, I am new to Github I didn't have much knowledge.

**Review by AlexGuteniev — APPROVED** [review]
Thanks. It is now good.

Please wait for a review by some of maintainers.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks, this is perfect! :heart_eyes_cat:

We merge PRs to our GitHub and MSVC-internal repos simultaneously. This is a semi-manual process, so we batch up PRs to save time. Your PR will be part of the next batch, likely this week. I'll post comments here when I'm preparing to mirror your PR, and when I merge it - no further action is necessary on your part. :tada:

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
I updated your PR description to say "resolves #4752" instead of "resolves issue #4752" - the magic words only work when they're immediately followed by an issue number, and the word "issue" interferes with that.

Thanks for updating this version macro, and congratulations on your first microsoft/STL commit! :tada: :heart_eyes_cat: :rocket:

This will be the value that appears in VS 2022 17.12 Preview 1 when that ships.

**Comment by ravixalgorithm** [comment]
Thanks, it's an honor

**Pull request merged**
