### PR TITLE
Bump _MSVC_STL_UPDATE for March 2020

### PR DESCRIPTION
**Pull request by WojciechMigda**
Description
===========
Bump _MSVC_STL_UPDATE for March 2020

Checklist
=========

Be sure you've read README.md and understand the scope of this repo.

If you're unsure about a box, leave it unchecked. A maintainer will help you.

- [x] Identifiers in product code changes are properly `_Ugly` as per
  https://eel.is/c++draft/lex.name#3.1 or there are no product code changes.
- [ ] The STL builds successfully and all tests have passed (must be manually
  verified by an STL maintainer before automated testing is enabled on GitHub,
  leave this unchecked for initial submission).
- [x] These changes introduce no known ABI breaks (adding members, renaming
  members, adding virtual functions, changing whether a type is an aggregate
  or trivially copyable, etc.).
- [x] These changes were written from scratch using only this repository,
  the C++ Working Draft (including any cited standards), other WG21 papers
  (excluding reference implementations outside of proposed standard wording),
  and LWG issues as reference material. If they were derived from a project
  that's already listed in NOTICE.txt, that's fine, but please mention it.
  If they were derived from any other project (including Boost and libc++,
  which are not yet listed in NOTICE.txt), you *must* mention it here,
  so we can determine whether the license is compatible and what else needs
  to be done.

### CODE REVIEW

**Comment by WojciechMigda** [comment]
> Looks good, thanks! I've linked issue #579 to this pull request. In the future, you can say "Fixes #579." in a pull request's description; see GitHub's documentation for ["Linking a pull request to an issue using a keyword"](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

Noted, thanks!

**Comment by BillyONeal** [comment]
@StephanTLavavej Should we just set it to April now and say "close enough" given that there won't be a VS release in the next 5 days?

**Comment by StephanTLavavej** [comment]
@BillyONeal I'd like April to provide a separate chance for a new GitHub contributor to get comfortable with the pull request process. 😸

**Comment by BillyONeal** [comment]
Sounds good!

**Comment by StephanTLavavej** [comment]
Thanks for keeping our version macro updated, and congratulations on your first microsoft/STL commit! 😺

**Pull request merged**
