### PR TITLE
<yvals_core.h> Update P2549 to new revision 

### LINKED ISSUE #2873: `<yvals_core.h>`: Update the reference to P2549 to P2549R1
The adopted revision of WG21-P2549 is [P2549R1](https://wg21.link/p2549r1), which only differs from R0 in some editorial changes.

We should just update the reference to it in `<yvals_core.h>`.

Code:

https://github.com/microsoft/STL/blob/ef62d3fa0b8e4e2406b9bb74e916e1ca8a1df802/stl/inc/yvals_core.h#L318

This issue is intended for a new contributor (especially one new to GitHub) to get started with the simplest possible change.

Please feel free to submit a pull request if there isn't one already linked here - no need to ask for permission! 😸

You can (and should) link your pull request to this issue using [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).
(in the PR description not the commit message)

### LINKED ISSUE #2940: P2549R1 `unexpected<E>::error()`
[P2549R1](https://wg21.link/P2549R1) `unexpected<E>::error()`

It is unclear to me whether the editors will increase the value of `__cpp_lib_expected` when merging this paper.

@miscco speculatively implemented this as part of #2643, so I believe that all that remains to be done is:

* [x] Double-check that there are no normative differences between R0 and R1.
* [x] Find out what's happening with the feature-test macro.
* [ ] Update this citation: https://github.com/microsoft/STL/blob/04ee87830a404437f1691d6a3e8809e4986d8493/stl/inc/yvals_core.h#L318

### PR DESCRIPTION
**Pull request by killerswin2**
### What have you changed and why?
Information:
    Changes yval_core.h to have the "correct" revision number

### Specify which Issue this PR Resolves.
closes #2873
closes #2940

### CODE REVIEW

**Review by fsb4000 — APPROVED** [review]
I think you should also add `closes #2940`

**Comment by killerswin2** [comment]
> I think you should also add `closes #2940`

Can do

**Review by frederick-vs-ja — APPROVED** [review]

**Review by StephanTLavavej — APPROVED** [review]

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating this paper citation, and congratulations on your first microsoft/STL commit! :rocket: :tada: :heart_eyes_cat:

**Comment by killerswin2** [comment]
Aw-shucks, thanks for the warm welcome.

**Pull request merged**
