### PR TITLE
Add stubbed xml doc files

### PR DESCRIPTION
**Pull request by RaulPerez1**
Add stub files for xml documentation

### CODE REVIEW

**Comment by BillyONeal** [comment]
I'm a bit concerned about just blindly including all of these because if they get out of date, that makes users who have thrown the /doc switch get compiler errors (if I recall correctly). Is that still the case or is there some means we can use to mitigate these getting broken due to edits over time?

**Comment by StephanTLavavej** [comment]
IIRC, we were interested in at least two things:

1. Validating these files. If the XML is damaged, or if it describes functions that no longer exist, that should be detected by the CI build.
2. Generating new stubs for new functions. (Lower priority.)

**Comment by BillyONeal** [comment]
Had a conversation with @RaulPerez1 in person and we discussed possible scenarios that one might want to enable:

Scenario 1: Base class doc applies to all children (_Atomic_storage::store) (exactly like Intellisense works today)
Scenario 2: Base class doc applies to no children at all (e.g. _Hash::emplace) (this might work if and only if the different types come from different headers)
Scenario 3: Metaprogramming garbage, visible doc and code have no relationship (e.g. ranges::advance) (???)

Scenario 4: We can check that documentation that we have written is actually attached to code the user can access.
Scenario 5: We can validate that everything is tagged documented (except exceptions).
Scenario 6: We can validate that everything new is documented.

I think we need some means of keeping the bits from getting stale before we want to actually commit this to master, though it's a good starting point for folks to add XML docs.

**Comment by StephanTLavavej** [comment]
We're closing this PR for now because:

* The requested compiler changes, or a plan to develop them, haven't arrived, and
* We're going to be busy with finishing C++20 and working on vNext through H1 2021 at least

We remain interested in improving the IDE experience for STL functions, so when these conditions change, we'll certainly consider resuming this (or similar) work in the future.

**Pull request closed without merging**
