### PR TITLE
add  [[msvc::intrinsic]] for some cast funcs.

### LINKED ISSUE #3548: STL: Mark simple casting free functions with `_MSVC_INTRINSIC`
#3182 added `[[msvc::intrinsic]]` attribute to the following reference-casting function templates:
- `forward`
- `forward_like`
- `move`
- `move_if_noexcept`

, which made MSVC treat a call to such a function equivalent to a simple `static_cast`.

Per local verifications and response from @cdacamar on Discord, it works for free functions which is equivalent to a cast. Here is an incomplete list of such functions, including internal helpers, in MSVC STL:
- Reference casting functions (I've verified locally some of them and believe `[[msvc::intrinsic]]` works)
  - `as_const` (in `<utility>`)
  - `_Possibly_const_range` (in `<xutility>`)
  - `_As_lvalue` (in `<ranges>`)
- Pointer casting functions (seemly works, but not very sure)
  - `_As_const_pointer` (in `<xutility>`)
- Integer/enumeration casting functions (seemly works, but not very sure)
  - `to_integer` (in `<cstddef>`)
  - `to_underlying` (in `<utility>`)

It would be great to find all of these functions and mark them with `_MSVC_INTRINSIC`.

Note that the `[[msvc::intrinsic]]` attribute currently doesn't work for member functions (both non-static and static ones), so even though `identity::operator()` looks like a good candidate, it's better not to mark it with `_MSVC_INTRINSIC` at this moment.

@JMazurkiewicz suggested that this might be a nice candidate for "good first issue".

### PR DESCRIPTION
**Pull request by infdahai**
1. use the macro `_MSVC_INTRINSIC` to add some cast functions' headers.
2. Fixes #3548

### CODE REVIEW

**Comment by infdahai** [comment]
> 

@microsoft-github-policy-service agree

**Comment by infdahai** [comment]
> @infdahai please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by infdahai** [comment]
@microsoft-github-policy-service agree

**Comment by fsb4000** [comment]
You should change your second point 
from
```
link https://github.com/microsoft/STL/issues/3548
```

to

```
Fixes #3548 
```

**Comment by infdahai** [comment]
> I looked at one of the failed tests.
> 
> ```c++
> #include <utility>
> 
> template <class _Ty>
> _MSVC_INTRINSIC constexpr std::add_const_t<_Ty>& as_const(_Ty& _Val) noexcept { // view _Val through const lenses
>     return _Val;
> }
> 
> int main()
> {
>     int i = 1729;
>     return (& as_const(i) == &i);
> }
> ```
> 
> `Error C2102 '&' requires l-value`
> 
> изображение
> 
> I'm not sure but it might be a compiler bug...

Thanks for the help.  I'll configure the environment to test it.

**Comment by StephanTLavavej** [comment]
@fsb4000 Yep, that looks like a compiler bug - thanks for the analysis. It should be reported to DevCom for the compiler team to investigate.

@infdahai There are remaining test failures (emitting a warning in the ranges `join_view` tests). One of the warnings is:

```
warning C4238: nonstandard extension used: class rvalue used as lvalue
```

so it's the same compiler bug.

In fact, the existing usage is affected! :scream_cat: :scream_cat: :scream_cat: Example with VS 2022 17.6 Preview 3:

```
C:\Temp>type meow.cpp
```
```cpp
#include <iostream>
#include <utility>
using namespace std;

template <typename T> void meow(T&& t) {
    cout << *&forward<T>(t) << endl;
}

int main() {
    int x = 1729;
    meow(x);
}
```
```
C:\Temp>cl /EHsc /nologo /W4 /std:c++latest meow.cpp && meow
meow.cpp
-1603273920
```

This works correctly with GCC: https://godbolt.org/z/fxMx6j3vb

FYI @cdacamar as you implemented this compiler optimization.

We believe that this bug effectively blocks any attempted expansion of the intrinsic optimization. The only reason the world hasn't exploded after we applied this to `move` and `forward` is that nobody can take the address of a `move`d object, and trying to take the address of a `forward`ed object directly is squirrely :chipmunk: (if you know it's an lvalue, why are you `forward`ing in the first place?).

**Comment by cdacamar** [comment]
> @fsb4000 Yep, that looks like a compiler bug - thanks for the analysis. It should be reported to DevCom for the compiler team to investigate.
> 
> @infdahai There are remaining test failures (emitting a warning in the ranges `join_view` tests). One of the warnings is:
> 
> ```
> warning C4238: nonstandard extension used: class rvalue used as lvalue
> ```
> 
> so it's the same compiler bug.
> 
> In fact, the existing usage is affected! 🙀 🙀 🙀 Example with VS 2022 17.6 Preview 3:
> 
> ```
> C:\Temp>type meow.cpp
> ```
> 
> ```c++
> #include <iostream>
> #include <utility>
> using namespace std;
> 
> template <typename T> void meow(T&& t) {
>     cout << *&forward<T>(t) << endl;
> }
> 
> int main() {
>     int x = 1729;
>     meow(x);
> }
> ```
> 
> ```
> C:\Temp>cl /EHsc /nologo /W4 /std:c++latest meow.cpp && meow
> meow.cpp
> -1603273920
> ```
> 
> This works correctly with GCC: https://godbolt.org/z/fxMx6j3vb
> 
> FYI @cdacamar as you implemented this compiler optimization.
> 
> We believe that this bug effectively blocks any attempted expansion of the intrinsic optimization. The only reason the world hasn't exploded after we applied this to `move` and `forward` is that nobody can take the address of a `move`d object, and trying to take the address of a `forward`ed object directly is squirrely 🐿️ (if you know it's an lvalue, why are you `forward`ing in the first place?).

This has already been fixed via [DevComm-1515406078](https://github.com/microsoft/STL/pull/3664#issuecomment-1515406078).  It will be part of 17.7.

**Comment by StephanTLavavej** [comment]
Ah, excellent, thanks Cameron! Then we can leave this PR in the blocked state until 17.7 Preview 2 ships and resume work then. :heart_eyes_cat: :heart_eyes_cat: :heart_eyes_cat:

**Comment by fsb4000** [comment]
@infdahai, revert your patch to the initial state 

https://github.com/microsoft/STL/pull/3664/commits/8e1667584a9d933908e524bf5e096a7b73d9783d

And then we will wait till VS 2022 17.7 Preview 2

**Comment by frederick-vs-ja** [comment]
After this PR gets unblocked, it seems better to add push and pop mechanism to affected headers (#3760).

**Comment by StephanTLavavej** [comment]
Unfortunately, 17.7 Preview 2 didn't contain an MSVC toolset update (MSVC and VS work in separate repos, it's complicated) so this is blocked until 17.7 Preview 3.

**Comment by WhiteSmoogy** [comment]
> I looked at one of the failed tests.
> 
> ```c++
> #include <utility>
> 
> template <class _Ty>
> _MSVC_INTRINSIC constexpr std::add_const_t<_Ty>& as_const(_Ty& _Val) noexcept { // view _Val through const lenses
>     return _Val;
> }
> 
> int main()
> {
>     int i = 1729;
>     return (& as_const(i) == &i);
> }
> ```
> 
> `Error C2102 '&' requires l-value`
> 
> изображение
> 
> I'm not sure but it might be a compiler bug...

I also encountered a similar problem, and it seems to be caused by the [[msvc::intrinsic]] attribute  of the std::forward
https://godbolt.org/z/T87d36Y6r

**Comment by fsb4000** [comment]
@WhiteSmoogy 17.7 Preview 3 should resolve your issue.

**Comment by infdahai** [comment]
Let's wait the new verson.

**Comment by StephanTLavavej** [comment]
I've pushed a conflict-free merge with `main`.

**Comment by StephanTLavavej** [comment]
There are still warnings even with 17.7 Preview 3.

**Comment by frederick-vs-ja** [comment]
@infdahai I've opened PR infdahai/STL#1 which should fix the failures in `tests/GH_002206_unreserved_names`.

`_As_lvalue` is still problematic. Perhaps we should drop the changes in `<ranges>` at this moment.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm *speculatively* mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for improving this codegen and congratulations on your first microsoft/STL commit! :tada: :rocket: :heart_eyes_cat:

**Pull request merged**
