### PR TITLE
add cmakeToolchain to CMakeSettings.json

### PR DESCRIPTION
**Pull request by fsb4000**
Today I tried to build STL from Visual Studio 2022 IDE (first try, before only command line)
And I had to add cmakeToolchain or I got an error: "BOOST NOT FOUND".
So I decided to contribute my changes.

изображение

### CODE REVIEW

**Comment by miscco** [comment]
It is a bit strange as it should already use the default vcpkg one

**Comment by fsb4000** [comment]
@miscco 
Could you try to build the stl from IDE?

**Comment by miscco** [comment]
I build it just last wek with the new toolchain

**Comment by fsb4000** [comment]
Strange. I did checkout main.
And vcpkg was found: " Found and using vcpkg toolchain file (C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake)."
But I still got error:

изображение

**Comment by fsb4000** [comment]
I got it. Without the patch it uses system vcpkg: (`C:\tools\vcpkg` in my case)
But stl vcpkg is `C:\Dev\STL\vcpkg`
Is this the expected behavior that vcpkg is taken from the system and not from stl?

**Comment by CaseyCarter** [comment]
So, IIUC, the question here is whether we want to override the user's choice of default vcpkg instance (which IIUC the user chose via `vcpkg integrate install`) and redirect to our internal vcpkg by default?

**Comment by fsb4000** [comment]
yes

**Comment by fsb4000** [comment]
if we decide that it is not worth overriding the user's choice of default vcpkg then we need to update the instruction: https://github.com/microsoft/STL#how-to-build-with-the-visual-studio-ide

**Comment by barcharcraz** [comment]
how is the "system" vcpkg defined? do you set it or does VS2022 set it?

**Comment by barcharcraz** [comment]
sidenote: I have a branch that removes CmakeSettings.json and adds CMakePresets.json (which is a similar feature provided natively by cmake), however I haven't opened a PR because it's somewhat broken at the moment in vscode.

**Comment by fsb4000** [comment]
@barcharcraz I installed it myself a couple days ago.

**Comment by StephanTLavavej** [comment]
I am far from an expert here, but using our internal vcpkg by default sounds like the right thing to do. Not only does it keep the repo in a self-contained known state, but we generally require the latest version of Boost, which a global install of vcpkg might not have. That said, my intuition for how vcpkg should be used may not reflect most vcpkg users, especially IDE users.

**Comment by fsb4000** [comment]
>fsb4000 has set an environment variable designed to override such a default

Not intentionally :) 

I just did again (new place):

```
git clone https://github.com/microsoft/vcpkg
.\vcpkg\bootstrap-vcpkg.bat
.\vcpkg\vcpkg integrate install
```

изображение

and it will use the place by default.
```
Found and using vcpkg toolchain file (C:/tools/test/vcpkg/scripts/buildsystems/vcpkg.cmake).
```
изображение

**Comment by barcharcraz** [comment]
I think we should either (or both)
1) adopt manifest mode, this would cause vcpkg to install the specified version of boost no matter what vcpkg installation is found.
2) document that if you run `vcpkg integrate install` visual studio will set the toolchain for you.

that said I don't have a huge problem with this PR, if we're all OK with overriding the vcpkg instance that the user requested by running integrate install.

**Review by barcharcraz — APPROVED** [review]

**Comment by fsb4000** [comment]
It works both console and IDE.

But now dependencies located there: 
`C:\Dev\STL\out\build\x64\vcpkg_installed`
`C:\Dev\STL\out\build\x86\vcpkg_installed`
etc.

When I switch between branches I usually delete the out folder(Maybe now I should delete without "vcpkg_installed" folder...)
Vcpkg will not rebuild boost and it will use caching, but there is a slight slowdown. 

изображение
изображение
изображение

**Comment by fsb4000** [comment]
I am not sure about Azure Pipeline.
Shoud I just delete the lines?
https://github.com/microsoft/STL/blob/a9321cfe53ea31a7e197d5d8336167d6ca3de8b6/azure-devops/vcpkg-dependencies.yml#L21-L38

**Comment by fsb4000** [comment]
`1257354a3ab0bebd8abe95281ca561537853578c` is from 
```
cd vcpkg
git rev-parse HEAD
```

изображение

`143` is from: https://github.com/microsoft/STL/blob/a9321cfe53ea31a7e197d5d8336167d6ca3de8b6/stl/inc/yvals_core.h#L563

**Comment by fsb4000** [comment]
now: https://dev.azure.com/vclibs/09a07da7-73b5-4bba-8263-2aad1a16c33d/_apis/build/builds/8709/logs/81
before: https://dev.azure.com/vclibs/09a07da7-73b5-4bba-8263-2aad1a16c33d/_apis/build/builds/8703/logs/83

it is definitely does not use vcpkg Caching.

**Comment by michael-herwig** [comment]
I think you need to update the cache hash for vcpkg. 

https://github.com/microsoft/STL/blob/721e3ad8952fce3447916ecdbff3863043686fa1/azure-devops/vcpkg-dependencies.yml#L17-L20

The cache hit loads a deprecated version of the vcpkg install directory. Further, the cache hit prevents the pipeline from uploading a new version of the cache.

You may want to hash the vcpkg manifest into the hash of the vpkg cache key, [see documentation](https://github.com/actions/cache#usage).
```yaml
    key: '"${{ parameters.targetPlatform }}" | "$(${{ parameters.vcpkgSHAVar }})" | ${{ hashFiles('vcpkg.json') }} | "2020-03-01.01"'
```
Or just update the date.

**Comment by fsb4000** [comment]
after #2151  my change is not needed.

**Pull request closed without merging**
