### PR TITLE
Add `[[noreturn]]` for some functions

### PR DESCRIPTION
**Pull request by achabense**
They are: `_Thrd_abort`, `_Thrd_exit` and `_ReportUnobservedException`.

### CODE REVIEW

**Comment by CaseyCarter** [comment]
The build is failing, I believe because `extern "C"` needs to appear before `[[noreturn]]` in a declaration. It's probably quicker to verify that the STL builds locally than to dig through the CI logs to find build errors ;)

**Comment by StephanTLavavej** [comment]
It's always important to verify that the STL builds locally (at least for x64) and passes some minimum set of tests before submitting a PR or pushing changes.

**Review by StephanTLavavej — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
This is reasonable for consistency although two of the functions are preserved for binary compatibility (i.e. are otherwise unused), the third is debug-only, and there are no changes to the sizes of the DLLs.

**Comment by StephanTLavavej** [comment]
I'm *speculatively* mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Thanks for noticing and fixing these inconsistencies! :no_entry: :door: :runner:

**Pull request merged**
