### PR TITLE
Documentation fix for #3779

### PR DESCRIPTION
**Pull request by Ashad001**
Fix [#3779](https://github.com/microsoft/STL/issues/3779)

### CODE REVIEW

**Review by JMazurkiewicz — CHANGES_REQUESTED** [review]
One more comment:
https://github.com/microsoft/STL/blob/15aea9852b557f70821651600e51d9a2b3b1a95e/stl/inc/expected#L1426

**Comment by Ashad001** [comment]
> One more comment:
> 
> https://github.com/microsoft/STL/blob/15aea9852b557f70821651600e51d9a2b3b1a95e/stl/inc/expected#L1426

Done

**Comment by Ashad001** [comment]
> 

@microsoft-github-policy-service agree

**Review by strega-nil-ms — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

**Comment by StephanTLavavej** [comment]
Thanks for updating these comments - and congratulations on your first microsoft/STL commit! :rocket: :tada: :heart_eyes_cat:

This will ship in VS 2022 17.8 Preview 1.

**Pull request merged**
