### PR TITLE
_NODISCARD for function objects

### PR DESCRIPTION
**Pull request by sam20908**
***Very likely*** partially addresses #206.

Note: `_NODISCARD` is already present for `ranges` function objects.

### CODE REVIEW

**Comment by sam20908** [comment]
There seems to be a missing test case for `compare_three_way` (noticed while I was fixing the test), should it be added?

**Comment by StephanTLavavej** [comment]
That file is indeed missing `compare_three_way` coverage, but we have extensive tests in a different file:

https://github.com/microsoft/STL/blob/19c683d70647f9d89d47f5a0ad25165fc8becbf3/tests/std/tests/P0896R4_P1614R2_comparisons/test.cpp#L222-L296

So you don't need to add anything. (You can if you really want to.)

**Comment by sam20908** [comment]
Ah okay. I'll just leave it as it is.

**Review by StephanTLavavej — APPROVED** [review]
Everything looks great here. :smile_cat:

**Review by CaseyCarter — APPROVED** [review]

**Comment by StephanTLavavej** [comment]
Status update: We simultaneously merge changes on GitHub and our MS-internal repo, so after Thanksgiving we should be able to batch up your PR with everything else that’s ready to merge and get this checked in for VS 2019 16.9 Preview 3.

**Comment by StephanTLavavej** [comment]
Thanks for improving the user experience with function objects, and congratulations on your first microsoft/STL commit! :tada: :smiley_cat: :rocket:

This will ship in VS 2019 16.9 Preview 3.

**Pull request merged**
